export const POINTS = {
  QUIZ_PERFECT_SCORE: 15,
  QUIZ_HIGH_SCORE: 10,
  QUIZ_GOOD_SCORE: 5,
  QUIZ_PASSING_SCORE: 2,

  FLASHCARDS: 4,
  MATCHING_GAME: 5,
  FILL_IN_BLANK: 7,

  NUMBERS_GAME_EASY: 3,
  NUMBERS_GAME_MEDIUM: 5,
  NUMBERS_GAME_MEDIUM_HARD: 7,
  NUMBERS_GAME_HARD: 10,
  VERB_FORMS_EASY: 1,
  VERB_FORMS_MEDIUM: 2,
  VERB_FORMS_HARD: 3,
  VERB_FORMS_BONUS: 5,

  NUMBERS_GAME_PERFECT_EASY: 2,
  NUMBERS_GAME_HIGH_EASY: 1,

  NUMBERS_GAME_PERFECT_MEDIUM: 3,
  NUMBERS_GAME_HIGH_MEDIUM: 2,

  NUMBERS_GAME_PERFECT_MEDIUM_HARD: 5,
  NUMBERS_GAME_HIGH_MEDIUM_HARD: 3,

  NUMBERS_GAME_PERFECT_HARD: 7,
  NUMBERS_GAME_HIGH_HARD: 4,

  GRAMMAR_GUIDE: 10,
  GRAMMAR_EXERCISE: 2,
  GRAMMAR_GUIDE_BASE: 5,
  GRAMMAR_GUIDE_PERFECT_BONUS: 5,
  SPEAKING_ACTIVITY: 6,
  ED_PRONUNCIATION: 6,
  ED_PRONUNCIATION_PERFECT: 10,
  MINIMAL_PAIRS: 6,
  ACTIVITY_COMPLETION: 3,

  DAILY_STREAK: 3,
  WEEKLY_STREAK: 25,

  ACHIEVEMENT_BONUS: 50,

  // Spanish Learning Points
  SPANISH_VOCABULARY_FLASHCARD: 4,
  SPANISH_VOCABULARY_PERFECT_SET: 8,
  SPANISH_NUMBERS_EASY: 3,
  SPANISH_NUMBERS_MEDIUM: 5,
  SPANISH_NUMBERS_HARD: 8,
  SPANISH_NUMBERS_PERFECT_ROUND: 5,
  SPANISH_VERB_CORRECT: 2,
  SPANISH_VERB_STREAK_5: 5,
  SPANISH_VERB_PERFECT_ROUND: 10,
  SPANISH_TIMED_SPEED_BONUS: 5,

  // Coding Challenge Points
  CODE_OUTPUT_PREDICTION: 3,
  CODE_OUTPUT_PREDICTION_STREAK_5: 5,
  CODE_BUG_HUNT_EASY: 3,
  CODE_BUG_HUNT_MEDIUM: 6,
  CODE_BUG_HUNT_HARD: 10,
  CODE_COMPLETION: 4,
  CODE_COMPLETION_PERFECT: 8,
  CODE_CONCEPT_MATCH: 5,
  CODING_STREAK_5: 10,
  CODING_PERFECT_ROUND: 15,
} as const;

export type PointsKey = keyof typeof POINTS;
