import type { SpanishVocabularyCard } from "@/types/activity";

export const colorsShapesCards: SpanishVocabularyCard[] = [
  // Colors
  {
    id: "rojo",
    spanish: "rojo",
    english: "red",
    pronunciation: "ROH-hoh",
    example: { spanish: "La manzana es roja.", english: "The apple is red." },
    gender: "masculine",
    difficulty: "beginner",
    category: "colors",
  },
  {
    id: "azul",
    spanish: "azul",
    english: "blue",
    pronunciation: "ah-SOOL",
    example: { spanish: "El cielo es azul.", english: "The sky is blue." },
    gender: null, // Invariable
    difficulty: "beginner",
    category: "colors",
  },
  {
    id: "verde",
    spanish: "verde",
    english: "green",
    pronunciation: "BEHR-deh",
    example: { spanish: "La hierba es verde.", english: "The grass is green." },
    gender: null, // Invariable
    difficulty: "beginner",
    category: "colors",
  },
  {
    id: "amarillo",
    spanish: "amarillo",
    english: "yellow",
    pronunciation: "ah-mah-REE-yoh",
    example: { spanish: "El sol es amarillo.", english: "The sun is yellow." },
    gender: "masculine",
    difficulty: "beginner",
    category: "colors",
  },
  {
    id: "naranja",
    spanish: "naranja",
    english: "orange",
    pronunciation: "nah-RAHN-hah",
    example: { spanish: "La naranja es naranja.", english: "The orange is orange." },
    gender: null, // Invariable for color
    difficulty: "beginner",
    category: "colors",
  },
  {
    id: "morado",
    spanish: "morado",
    english: "purple",
    pronunciation: "moh-RAH-doh",
    example: { spanish: "Las uvas son moradas.", english: "The grapes are purple." },
    gender: "masculine",
    difficulty: "beginner",
    category: "colors",
  },
  {
    id: "rosa",
    spanish: "rosa",
    english: "pink",
    pronunciation: "ROH-sah",
    example: { spanish: "El vestido es rosa.", english: "The dress is pink." },
    gender: null, // Invariable
    difficulty: "beginner",
    category: "colors",
  },
  {
    id: "blanco",
    spanish: "blanco",
    english: "white",
    pronunciation: "BLAHN-koh",
    example: { spanish: "La nieve es blanca.", english: "The snow is white." },
    gender: "masculine",
    difficulty: "beginner",
    category: "colors",
  },
  {
    id: "negro",
    spanish: "negro",
    english: "black",
    pronunciation: "NEH-groh",
    example: { spanish: "El gato es negro.", english: "The cat is black." },
    gender: "masculine",
    difficulty: "beginner",
    category: "colors",
  },
  {
    id: "gris",
    spanish: "gris",
    english: "gray",
    pronunciation: "grees",
    example: { spanish: "El elefante es gris.", english: "The elephant is gray." },
    gender: null, // Invariable
    difficulty: "beginner",
    category: "colors",
  },
  {
    id: "marron",
    spanish: "marrón",
    english: "brown",
    pronunciation: "mah-RROHN",
    example: { spanish: "El chocolate es marrón.", english: "Chocolate is brown." },
    gender: null, // Invariable
    difficulty: "beginner",
    category: "colors",
  },
  // Shapes
  {
    id: "circulo",
    spanish: "el círculo",
    english: "the circle",
    pronunciation: "SEER-koo-loh",
    example: { spanish: "La pizza es un círculo.", english: "The pizza is a circle." },
    gender: "masculine",
    difficulty: "beginner",
    category: "shapes",
  },
  {
    id: "cuadrado",
    spanish: "el cuadrado",
    english: "the square",
    pronunciation: "kwah-DRAH-doh",
    example: { spanish: "La ventana es un cuadrado.", english: "The window is a square." },
    gender: "masculine",
    difficulty: "beginner",
    category: "shapes",
  },
  {
    id: "triangulo",
    spanish: "el triángulo",
    english: "the triangle",
    pronunciation: "tree-AHN-goo-loh",
    example: { spanish: "Las pirámides tienen triángulos.", english: "Pyramids have triangles." },
    gender: "masculine",
    difficulty: "beginner",
    category: "shapes",
  },
  {
    id: "rectangulo",
    spanish: "el rectángulo",
    english: "the rectangle",
    pronunciation: "rehk-TAHN-goo-loh",
    example: { spanish: "La puerta es un rectángulo.", english: "The door is a rectangle." },
    gender: "masculine",
    difficulty: "intermediate",
    category: "shapes",
  },
];

export const colorsShapesVocabulary = {
  id: "spanish-vocab-colors",
  title: "Colors & Shapes",
  description: "Learn colors and basic shapes in Spanish",
  cards: colorsShapesCards,
  difficulty: "beginner" as const,
  cardCount: colorsShapesCards.length,
};
