import type { SpanishVocabularyCard, SpanishVerbConjugation } from "@/types/activity";

export const commonVerbCards: SpanishVocabularyCard[] = [
  {
    id: "ser",
    spanish: "ser",
    english: "to be (permanent)",
    pronunciation: "sehr",
    example: { spanish: "Soy estudiante.", english: "I am a student." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "estar",
    spanish: "estar",
    english: "to be (temporary/location)",
    pronunciation: "ehs-TAHR",
    example: { spanish: "Estoy feliz.", english: "I am happy." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "tener",
    spanish: "tener",
    english: "to have",
    pronunciation: "teh-NEHR",
    example: { spanish: "Tengo un perro.", english: "I have a dog." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "hacer",
    spanish: "hacer",
    english: "to do / to make",
    pronunciation: "ah-SEHR",
    example: { spanish: "Hago la tarea.", english: "I do the homework." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "ir",
    spanish: "ir",
    english: "to go",
    pronunciation: "eer",
    example: { spanish: "Voy al parque.", english: "I go to the park." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "hablar",
    spanish: "hablar",
    english: "to speak / to talk",
    pronunciation: "ah-BLAHR",
    example: { spanish: "Hablo español.", english: "I speak Spanish." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "comer",
    spanish: "comer",
    english: "to eat",
    pronunciation: "koh-MEHR",
    example: { spanish: "Como pizza.", english: "I eat pizza." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "beber",
    spanish: "beber",
    english: "to drink",
    pronunciation: "beh-BEHR",
    example: { spanish: "Bebo agua.", english: "I drink water." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "vivir",
    spanish: "vivir",
    english: "to live",
    pronunciation: "bee-BEER",
    example: { spanish: "Vivo en Nueva York.", english: "I live in New York." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "escribir",
    spanish: "escribir",
    english: "to write",
    pronunciation: "ehs-kree-BEER",
    example: { spanish: "Escribo una carta.", english: "I write a letter." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "leer",
    spanish: "leer",
    english: "to read",
    pronunciation: "leh-EHR",
    example: { spanish: "Leo un libro.", english: "I read a book." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "querer",
    spanish: "querer",
    english: "to want / to love",
    pronunciation: "keh-REHR",
    example: { spanish: "Quiero café.", english: "I want coffee." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "poder",
    spanish: "poder",
    english: "to be able to / can",
    pronunciation: "poh-DEHR",
    example: { spanish: "Puedo ayudar.", english: "I can help." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "saber",
    spanish: "saber",
    english: "to know (facts)",
    pronunciation: "sah-BEHR",
    example: { spanish: "Sé la respuesta.", english: "I know the answer." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "conocer",
    spanish: "conocer",
    english: "to know (people/places)",
    pronunciation: "koh-noh-SEHR",
    example: { spanish: "Conozco a María.", english: "I know María." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "trabajar",
    spanish: "trabajar",
    english: "to work",
    pronunciation: "trah-bah-HAHR",
    example: { spanish: "Trabajo en una oficina.", english: "I work in an office." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "estudiar",
    spanish: "estudiar",
    english: "to study",
    pronunciation: "ehs-too-DYAHR",
    example: { spanish: "Estudio español.", english: "I study Spanish." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "comprar",
    spanish: "comprar",
    english: "to buy",
    pronunciation: "kohm-PRAHR",
    example: { spanish: "Compro pan.", english: "I buy bread." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "venir",
    spanish: "venir",
    english: "to come",
    pronunciation: "beh-NEER",
    example: { spanish: "Vengo de España.", english: "I come from Spain." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "salir",
    spanish: "salir",
    english: "to leave / to go out",
    pronunciation: "sah-LEER",
    example: { spanish: "Salgo a las ocho.", english: "I leave at eight." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "dar",
    spanish: "dar",
    english: "to give",
    pronunciation: "dahr",
    example: { spanish: "Doy un regalo.", english: "I give a gift." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "decir",
    spanish: "decir",
    english: "to say / to tell",
    pronunciation: "deh-SEER",
    example: { spanish: "Digo la verdad.", english: "I tell the truth." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "pensar",
    spanish: "pensar",
    english: "to think",
    pronunciation: "pehn-SAHR",
    example: { spanish: "Pienso en ti.", english: "I think about you." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "empezar",
    spanish: "empezar",
    english: "to begin / to start",
    pronunciation: "ehm-peh-SAHR",
    example: { spanish: "Empiezo a trabajar.", english: "I start working." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "entender",
    spanish: "entender",
    english: "to understand",
    pronunciation: "ehn-tehn-DEHR",
    example: { spanish: "No entiendo.", english: "I don't understand." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "jugar",
    spanish: "jugar",
    english: "to play (games)",
    pronunciation: "hoo-GAHR",
    example: { spanish: "Juego al fútbol.", english: "I play soccer." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "dormir",
    spanish: "dormir",
    english: "to sleep",
    pronunciation: "dohr-MEER",
    example: { spanish: "Duermo mucho.", english: "I sleep a lot." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "poner",
    spanish: "poner",
    english: "to put / to place",
    pronunciation: "poh-NEHR",
    example: { spanish: "Pongo el libro aquí.", english: "I put the book here." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "mirar",
    spanish: "mirar",
    english: "to look / to watch",
    pronunciation: "mee-RAHR",
    example: { spanish: "Miro la televisión.", english: "I watch television." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "escuchar",
    spanish: "escuchar",
    english: "to listen",
    pronunciation: "ehs-koo-CHAHR",
    example: { spanish: "Escucho música.", english: "I listen to music." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "llegar",
    spanish: "llegar",
    english: "to arrive",
    pronunciation: "yeh-GAHR",
    example: { spanish: "Llego tarde.", english: "I arrive late." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "llevar",
    spanish: "llevar",
    english: "to carry / to wear",
    pronunciation: "yeh-BAHR",
    example: { spanish: "Llevo una chaqueta.", english: "I wear a jacket." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "tomar",
    spanish: "tomar",
    english: "to take / to drink",
    pronunciation: "toh-MAHR",
    example: { spanish: "Tomo un café.", english: "I drink a coffee." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "pasar",
    spanish: "pasar",
    english: "to pass / to happen / spend time",
    pronunciation: "pah-SAHR",
    example: { spanish: "Paso tiempo con mi familia.", english: "I spend time with my family." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "llamar",
    spanish: "llamar",
    english: "to call",
    pronunciation: "yah-MAHR",
    example: { spanish: "Llamo a mi madre.", english: "I call my mother." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "esperar",
    spanish: "esperar",
    english: "to wait / to hope",
    pronunciation: "ehs-peh-RAHR",
    example: { spanish: "Espero el autobús.", english: "I wait for the bus." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "deber",
    spanish: "deber",
    english: "to owe / must / should",
    pronunciation: "deh-BEHR",
    example: { spanish: "Debo estudiar más.", english: "I must study more." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "creer",
    spanish: "creer",
    english: "to believe",
    pronunciation: "kreh-EHR",
    example: { spanish: "Creo que sí.", english: "I believe so." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "correr",
    spanish: "correr",
    english: "to run",
    pronunciation: "koh-RREHR",
    example: { spanish: "Corro en el parque.", english: "I run in the park." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "abrir",
    spanish: "abrir",
    english: "to open",
    pronunciation: "ah-BREER",
    example: { spanish: "Abro la puerta.", english: "I open the door." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "recibir",
    spanish: "recibir",
    english: "to receive",
    pronunciation: "reh-see-BEER",
    example: { spanish: "Recibo un mensaje.", english: "I receive a message." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
];

// Full conjugation data for the verb game
export const verbConjugations: SpanishVerbConjugation[] = [
  // Regular -AR verbs
  {
    infinitive: "hablar",
    english: "to speak",
    type: "ar",
    present: {
      yo: "hablo",
      tu: "hablas",
      el: "habla",
      nosotros: "hablamos",
      ellos: "hablan",
    },
    preterite: {
      yo: "hablé",
      tu: "hablaste",
      el: "habló",
      nosotros: "hablamos",
      ellos: "hablaron",
    },
  },
  {
    infinitive: "trabajar",
    english: "to work",
    type: "ar",
    present: {
      yo: "trabajo",
      tu: "trabajas",
      el: "trabaja",
      nosotros: "trabajamos",
      ellos: "trabajan",
    },
    preterite: {
      yo: "trabajé",
      tu: "trabajaste",
      el: "trabajó",
      nosotros: "trabajamos",
      ellos: "trabajaron",
    },
  },
  {
    infinitive: "estudiar",
    english: "to study",
    type: "ar",
    present: {
      yo: "estudio",
      tu: "estudias",
      el: "estudia",
      nosotros: "estudiamos",
      ellos: "estudian",
    },
    preterite: {
      yo: "estudié",
      tu: "estudiaste",
      el: "estudió",
      nosotros: "estudiamos",
      ellos: "estudiaron",
    },
  },
  {
    infinitive: "comprar",
    english: "to buy",
    type: "ar",
    present: {
      yo: "compro",
      tu: "compras",
      el: "compra",
      nosotros: "compramos",
      ellos: "compran",
    },
    preterite: {
      yo: "compré",
      tu: "compraste",
      el: "compró",
      nosotros: "compramos",
      ellos: "compraron",
    },
  },
  {
    infinitive: "mirar",
    english: "to look/watch",
    type: "ar",
    present: { yo: "miro", tu: "miras", el: "mira", nosotros: "miramos", ellos: "miran" },
    preterite: { yo: "miré", tu: "miraste", el: "miró", nosotros: "miramos", ellos: "miraron" },
  },
  {
    infinitive: "escuchar",
    english: "to listen",
    type: "ar",
    present: { yo: "escucho", tu: "escuchas", el: "escucha", nosotros: "escuchamos", ellos: "escuchan" },
    preterite: { yo: "escuché", tu: "escuchaste", el: "escuchó", nosotros: "escuchamos", ellos: "escucharon" },
  },
  {
    infinitive: "llegar",
    english: "to arrive",
    type: "ar",
    present: { yo: "llego", tu: "llegas", el: "llega", nosotros: "llegamos", ellos: "llegan" },
    preterite: { yo: "llegué", tu: "llegaste", el: "llegó", nosotros: "llegamos", ellos: "llegaron" },
  },
  {
    infinitive: "llevar",
    english: "to carry/wear",
    type: "ar",
    present: { yo: "llevo", tu: "llevas", el: "lleva", nosotros: "llevamos", ellos: "llevan" },
    preterite: { yo: "llevé", tu: "llevaste", el: "llevó", nosotros: "llevamos", ellos: "llevaron" },
  },
  {
    infinitive: "tomar",
    english: "to take/drink",
    type: "ar",
    present: { yo: "tomo", tu: "tomas", el: "toma", nosotros: "tomamos", ellos: "toman" },
    preterite: { yo: "tomé", tu: "tomaste", el: "tomó", nosotros: "tomamos", ellos: "tomaron" },
  },
  {
    infinitive: "pasar",
    english: "to pass/happen",
    type: "ar",
    present: { yo: "paso", tu: "pasas", el: "pasa", nosotros: "pasamos", ellos: "pasan" },
    preterite: { yo: "pasé", tu: "pasaste", el: "pasó", nosotros: "pasamos", ellos: "pasaron" },
  },
  {
    infinitive: "llamar",
    english: "to call",
    type: "ar",
    present: { yo: "llamo", tu: "llamas", el: "llama", nosotros: "llamamos", ellos: "llaman" },
    preterite: { yo: "llamé", tu: "llamaste", el: "llamó", nosotros: "llamamos", ellos: "llamaron" },
  },
  {
    infinitive: "esperar",
    english: "to wait/hope",
    type: "ar",
    present: { yo: "espero", tu: "esperas", el: "espera", nosotros: "esperamos", ellos: "esperan" },
    preterite: { yo: "esperé", tu: "esperaste", el: "esperó", nosotros: "esperamos", ellos: "esperaron" },
  },
  // Regular -ER verbs
  {
    infinitive: "comer",
    english: "to eat",
    type: "er",
    present: {
      yo: "como",
      tu: "comes",
      el: "come",
      nosotros: "comemos",
      ellos: "comen",
    },
    preterite: {
      yo: "comí",
      tu: "comiste",
      el: "comió",
      nosotros: "comimos",
      ellos: "comieron",
    },
  },
  {
    infinitive: "beber",
    english: "to drink",
    type: "er",
    present: {
      yo: "bebo",
      tu: "bebes",
      el: "bebe",
      nosotros: "bebemos",
      ellos: "beben",
    },
    preterite: {
      yo: "bebí",
      tu: "bebiste",
      el: "bebió",
      nosotros: "bebimos",
      ellos: "bebieron",
    },
  },
  {
    infinitive: "leer",
    english: "to read",
    type: "er",
    present: {
      yo: "leo",
      tu: "lees",
      el: "lee",
      nosotros: "leemos",
      ellos: "leen",
    },
    preterite: {
      yo: "leí",
      tu: "leíste",
      el: "leyó",
      nosotros: "leímos",
      ellos: "leyeron",
    },
  },
  {
    infinitive: "deber",
    english: "to owe/must",
    type: "er",
    present: { yo: "debo", tu: "debes", el: "debe", nosotros: "debemos", ellos: "deben" },
    preterite: { yo: "debí", tu: "debiste", el: "debió", nosotros: "debimos", ellos: "debieron" },
  },
  {
    infinitive: "creer",
    english: "to believe",
    type: "er",
    present: { yo: "creo", tu: "crees", el: "cree", nosotros: "creemos", ellos: "creen" },
    preterite: { yo: "creí", tu: "creíste", el: "creyó", nosotros: "creímos", ellos: "creyeron" },
  },
  {
    infinitive: "correr",
    english: "to run",
    type: "er",
    present: { yo: "corro", tu: "corres", el: "corre", nosotros: "corremos", ellos: "corren" },
    preterite: { yo: "corrí", tu: "corriste", el: "corrió", nosotros: "corrimos", ellos: "corrieron" },
  },
  // Regular -IR verbs
  {
    infinitive: "vivir",
    english: "to live",
    type: "ir",
    present: {
      yo: "vivo",
      tu: "vives",
      el: "vive",
      nosotros: "vivimos",
      ellos: "viven",
    },
    preterite: {
      yo: "viví",
      tu: "viviste",
      el: "vivió",
      nosotros: "vivimos",
      ellos: "vivieron",
    },
  },
  {
    infinitive: "escribir",
    english: "to write",
    type: "ir",
    present: {
      yo: "escribo",
      tu: "escribes",
      el: "escribe",
      nosotros: "escribimos",
      ellos: "escriben",
    },
    preterite: {
      yo: "escribí",
      tu: "escribiste",
      el: "escribió",
      nosotros: "escribimos",
      ellos: "escribieron",
    },
  },
  {
    infinitive: "abrir",
    english: "to open",
    type: "ir",
    present: { yo: "abro", tu: "abres", el: "abre", nosotros: "abrimos", ellos: "abren" },
    preterite: { yo: "abrí", tu: "abriste", el: "abrió", nosotros: "abrimos", ellos: "abrieron" },
  },
  {
    infinitive: "recibir",
    english: "to receive",
    type: "ir",
    present: { yo: "recibo", tu: "recibes", el: "recibe", nosotros: "recibimos", ellos: "reciben" },
    preterite: { yo: "recibí", tu: "recibiste", el: "recibió", nosotros: "recibimos", ellos: "recibieron" },
  },
  // Irregular verbs
  {
    infinitive: "ser",
    english: "to be (permanent)",
    type: "irregular",
    present: {
      yo: "soy",
      tu: "eres",
      el: "es",
      nosotros: "somos",
      ellos: "son",
    },
    preterite: {
      yo: "fui",
      tu: "fuiste",
      el: "fue",
      nosotros: "fuimos",
      ellos: "fueron",
    },
    irregularNote: "Completely irregular in all forms",
  },
  {
    infinitive: "estar",
    english: "to be (temporary)",
    type: "irregular",
    present: {
      yo: "estoy",
      tu: "estás",
      el: "está",
      nosotros: "estamos",
      ellos: "están",
    },
    preterite: {
      yo: "estuve",
      tu: "estuviste",
      el: "estuvo",
      nosotros: "estuvimos",
      ellos: "estuvieron",
    },
    irregularNote: "Irregular yo form in present; stem change in preterite",
  },
  {
    infinitive: "ir",
    english: "to go",
    type: "irregular",
    present: {
      yo: "voy",
      tu: "vas",
      el: "va",
      nosotros: "vamos",
      ellos: "van",
    },
    preterite: {
      yo: "fui",
      tu: "fuiste",
      el: "fue",
      nosotros: "fuimos",
      ellos: "fueron",
    },
    irregularNote: "Completely irregular; same preterite as 'ser'",
  },
  {
    infinitive: "tener",
    english: "to have",
    type: "irregular",
    present: {
      yo: "tengo",
      tu: "tienes",
      el: "tiene",
      nosotros: "tenemos",
      ellos: "tienen",
    },
    preterite: {
      yo: "tuve",
      tu: "tuviste",
      el: "tuvo",
      nosotros: "tuvimos",
      ellos: "tuvieron",
    },
    irregularNote: "e→ie stem change; irregular yo form",
  },
  {
    infinitive: "hacer",
    english: "to do/make",
    type: "irregular",
    present: {
      yo: "hago",
      tu: "haces",
      el: "hace",
      nosotros: "hacemos",
      ellos: "hacen",
    },
    preterite: {
      yo: "hice",
      tu: "hiciste",
      el: "hizo",
      nosotros: "hicimos",
      ellos: "hicieron",
    },
    irregularNote: "Irregular yo form; c→z in third person preterite",
  },
  {
    infinitive: "querer",
    english: "to want/love",
    type: "irregular",
    present: {
      yo: "quiero",
      tu: "quieres",
      el: "quiere",
      nosotros: "queremos",
      ellos: "quieren",
    },
    preterite: {
      yo: "quise",
      tu: "quisiste",
      el: "quiso",
      nosotros: "quisimos",
      ellos: "quisieron",
    },
    irregularNote: "e→ie stem change in present",
  },
  {
    infinitive: "poder",
    english: "to be able/can",
    type: "irregular",
    present: {
      yo: "puedo",
      tu: "puedes",
      el: "puede",
      nosotros: "podemos",
      ellos: "pueden",
    },
    preterite: {
      yo: "pude",
      tu: "pudiste",
      el: "pudo",
      nosotros: "pudimos",
      ellos: "pudieron",
    },
    irregularNote: "o→ue stem change in present",
  },
  {
    infinitive: "venir",
    english: "to come",
    type: "irregular",
    present: {
      yo: "vengo",
      tu: "vienes",
      el: "viene",
      nosotros: "venimos",
      ellos: "vienen",
    },
    preterite: {
      yo: "vine",
      tu: "viniste",
      el: "vino",
      nosotros: "vinimos",
      ellos: "vinieron",
    },
    irregularNote: "e→ie stem change; irregular yo form",
  },
  {
    infinitive: "saber",
    english: "to know (facts)",
    type: "irregular",
    present: {
      yo: "sé",
      tu: "sabes",
      el: "sabe",
      nosotros: "sabemos",
      ellos: "saben",
    },
    preterite: {
      yo: "supe",
      tu: "supiste",
      el: "supo",
      nosotros: "supimos",
      ellos: "supieron",
    },
    irregularNote: "Irregular yo form in present",
  },
  {
    infinitive: "conocer",
    english: "to know (people)",
    type: "irregular",
    present: {
      yo: "conozco",
      tu: "conoces",
      el: "conoce",
      nosotros: "conocemos",
      ellos: "conocen",
    },
    preterite: {
      yo: "conocí",
      tu: "conociste",
      el: "conoció",
      nosotros: "conocimos",
      ellos: "conocieron",
    },
    irregularNote: "c→zc in yo form (present)",
  },
  {
    infinitive: "dar",
    english: "to give",
    type: "irregular",
    present: { yo: "doy", tu: "das", el: "da", nosotros: "damos", ellos: "dan" },
    preterite: { yo: "di", tu: "diste", el: "dio", nosotros: "dimos", ellos: "dieron" },
    irregularNote: "Irregular yo form in present; completely irregular preterite",
  },
  {
    infinitive: "decir",
    english: "to say/tell",
    type: "irregular",
    present: { yo: "digo", tu: "dices", el: "dice", nosotros: "decimos", ellos: "dicen" },
    preterite: { yo: "dije", tu: "dijiste", el: "dijo", nosotros: "dijimos", ellos: "dijeron" },
    irregularNote: "e→i stem change in present; completely irregular preterite",
  },
  {
    infinitive: "pensar",
    english: "to think",
    type: "irregular",
    present: { yo: "pienso", tu: "piensas", el: "piensa", nosotros: "pensamos", ellos: "piensan" },
    preterite: { yo: "pensé", tu: "pensaste", el: "pensó", nosotros: "pensamos", ellos: "pensaron" },
    irregularNote: "e→ie stem change in present",
  },
  {
    infinitive: "empezar",
    english: "to begin/start",
    type: "irregular",
    present: { yo: "empiezo", tu: "empiezas", el: "empieza", nosotros: "empezamos", ellos: "empiezan" },
    preterite: { yo: "empecé", tu: "empezaste", el: "empezó", nosotros: "empezamos", ellos: "empezaron" },
    irregularNote: "e→ie stem change in present; z→c spelling change in yo preterite",
  },
  {
    infinitive: "entender",
    english: "to understand",
    type: "irregular",
    present: { yo: "entiendo", tu: "entiendes", el: "entiende", nosotros: "entendemos", ellos: "entienden" },
    preterite: { yo: "entendí", tu: "entendiste", el: "entendió", nosotros: "entendimos", ellos: "entendieron" },
    irregularNote: "e→ie stem change in present",
  },
  {
    infinitive: "jugar",
    english: "to play (games)",
    type: "irregular",
    present: { yo: "juego", tu: "juegas", el: "juega", nosotros: "jugamos", ellos: "juegan" },
    preterite: { yo: "jugué", tu: "jugaste", el: "jugó", nosotros: "jugamos", ellos: "jugaron" },
    irregularNote: "u→ue stem change in present; g→gu spelling change in yo preterite",
  },
  {
    infinitive: "dormir",
    english: "to sleep",
    type: "irregular",
    present: { yo: "duermo", tu: "duermes", el: "duerme", nosotros: "dormimos", ellos: "duermen" },
    preterite: { yo: "dormí", tu: "dormiste", el: "durmió", nosotros: "dormimos", ellos: "durmieron" },
    irregularNote: "o→ue stem change in present; o→u stem change in 3rd person preterite",
  },
  {
    infinitive: "poner",
    english: "to put/place",
    type: "irregular",
    present: { yo: "pongo", tu: "pones", el: "pone", nosotros: "ponemos", ellos: "ponen" },
    preterite: { yo: "puse", tu: "pusiste", el: "puso", nosotros: "pusimos", ellos: "pusieron" },
    irregularNote: "Irregular yo form in present; completely irregular preterite",
  },
];

export const commonVerbsVocabulary = {
  id: "spanish-vocab-verbs",
  title: "Common Verbs",
  description: "Essential Spanish verbs for everyday communication",
  cards: commonVerbCards,
  difficulty: "beginner" as const,
  cardCount: commonVerbCards.length,
};

/**
 * Get verbs by type for the verb game
 */
export function getVerbsByType(types: ("ar" | "er" | "ir" | "irregular")[]): SpanishVerbConjugation[] {
  return verbConjugations.filter((v) => types.includes(v.type));
}

/**
 * Check if a conjugation answer is correct (handles accents)
 */
export function checkConjugation(expected: string, userAnswer: string): boolean {
  const normalize = (str: string) =>
    str
      .toLowerCase()
      .trim()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "");

  return normalize(expected) === normalize(userAnswer);
}
