import type { SpanishVocabularyCard, SpanishVerbConjugation } from "@/types/activity";

export const commonVerbCards: SpanishVocabularyCard[] = [
  {
    id: "ser",
    spanish: "ser",
    english: "to be (permanent)",
    pronunciation: "sehr",
    example: { spanish: "Soy estudiante.", english: "I am a student." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "estar",
    spanish: "estar",
    english: "to be (temporary/location)",
    pronunciation: "ehs-TAHR",
    example: { spanish: "Estoy feliz.", english: "I am happy." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "tener",
    spanish: "tener",
    english: "to have",
    pronunciation: "teh-NEHR",
    example: { spanish: "Tengo un perro.", english: "I have a dog." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "hacer",
    spanish: "hacer",
    english: "to do / to make",
    pronunciation: "ah-SEHR",
    example: { spanish: "Hago la tarea.", english: "I do the homework." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "ir",
    spanish: "ir",
    english: "to go",
    pronunciation: "eer",
    example: { spanish: "Voy al parque.", english: "I go to the park." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "hablar",
    spanish: "hablar",
    english: "to speak / to talk",
    pronunciation: "ah-BLAHR",
    example: { spanish: "Hablo español.", english: "I speak Spanish." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "comer",
    spanish: "comer",
    english: "to eat",
    pronunciation: "koh-MEHR",
    example: { spanish: "Como pizza.", english: "I eat pizza." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "beber",
    spanish: "beber",
    english: "to drink",
    pronunciation: "beh-BEHR",
    example: { spanish: "Bebo agua.", english: "I drink water." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "vivir",
    spanish: "vivir",
    english: "to live",
    pronunciation: "bee-BEER",
    example: { spanish: "Vivo en Nueva York.", english: "I live in New York." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "escribir",
    spanish: "escribir",
    english: "to write",
    pronunciation: "ehs-kree-BEER",
    example: { spanish: "Escribo una carta.", english: "I write a letter." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "leer",
    spanish: "leer",
    english: "to read",
    pronunciation: "leh-EHR",
    example: { spanish: "Leo un libro.", english: "I read a book." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "querer",
    spanish: "querer",
    english: "to want / to love",
    pronunciation: "keh-REHR",
    example: { spanish: "Quiero café.", english: "I want coffee." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "poder",
    spanish: "poder",
    english: "to be able to / can",
    pronunciation: "poh-DEHR",
    example: { spanish: "Puedo ayudar.", english: "I can help." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "saber",
    spanish: "saber",
    english: "to know (facts)",
    pronunciation: "sah-BEHR",
    example: { spanish: "Sé la respuesta.", english: "I know the answer." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "conocer",
    spanish: "conocer",
    english: "to know (people/places)",
    pronunciation: "koh-noh-SEHR",
    example: { spanish: "Conozco a María.", english: "I know María." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "trabajar",
    spanish: "trabajar",
    english: "to work",
    pronunciation: "trah-bah-HAHR",
    example: { spanish: "Trabajo en una oficina.", english: "I work in an office." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "estudiar",
    spanish: "estudiar",
    english: "to study",
    pronunciation: "ehs-too-DYAHR",
    example: { spanish: "Estudio español.", english: "I study Spanish." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "comprar",
    spanish: "comprar",
    english: "to buy",
    pronunciation: "kohm-PRAHR",
    example: { spanish: "Compro pan.", english: "I buy bread." },
    gender: null,
    difficulty: "beginner",
    category: "verbs",
  },
  {
    id: "venir",
    spanish: "venir",
    english: "to come",
    pronunciation: "beh-NEER",
    example: { spanish: "Vengo de España.", english: "I come from Spain." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
  {
    id: "salir",
    spanish: "salir",
    english: "to leave / to go out",
    pronunciation: "sah-LEER",
    example: { spanish: "Salgo a las ocho.", english: "I leave at eight." },
    gender: null,
    difficulty: "intermediate",
    category: "verbs",
  },
];

// Full conjugation data for the verb game
export const verbConjugations: SpanishVerbConjugation[] = [
  // Regular -AR verbs
  {
    infinitive: "hablar",
    english: "to speak",
    type: "ar",
    present: {
      yo: "hablo",
      tu: "hablas",
      el: "habla",
      nosotros: "hablamos",
      ellos: "hablan",
    },
    preterite: {
      yo: "hablé",
      tu: "hablaste",
      el: "habló",
      nosotros: "hablamos",
      ellos: "hablaron",
    },
  },
  {
    infinitive: "trabajar",
    english: "to work",
    type: "ar",
    present: {
      yo: "trabajo",
      tu: "trabajas",
      el: "trabaja",
      nosotros: "trabajamos",
      ellos: "trabajan",
    },
    preterite: {
      yo: "trabajé",
      tu: "trabajaste",
      el: "trabajó",
      nosotros: "trabajamos",
      ellos: "trabajaron",
    },
  },
  {
    infinitive: "estudiar",
    english: "to study",
    type: "ar",
    present: {
      yo: "estudio",
      tu: "estudias",
      el: "estudia",
      nosotros: "estudiamos",
      ellos: "estudian",
    },
    preterite: {
      yo: "estudié",
      tu: "estudiaste",
      el: "estudió",
      nosotros: "estudiamos",
      ellos: "estudiaron",
    },
  },
  {
    infinitive: "comprar",
    english: "to buy",
    type: "ar",
    present: {
      yo: "compro",
      tu: "compras",
      el: "compra",
      nosotros: "compramos",
      ellos: "compran",
    },
    preterite: {
      yo: "compré",
      tu: "compraste",
      el: "compró",
      nosotros: "compramos",
      ellos: "compraron",
    },
  },
  // Regular -ER verbs
  {
    infinitive: "comer",
    english: "to eat",
    type: "er",
    present: {
      yo: "como",
      tu: "comes",
      el: "come",
      nosotros: "comemos",
      ellos: "comen",
    },
    preterite: {
      yo: "comí",
      tu: "comiste",
      el: "comió",
      nosotros: "comimos",
      ellos: "comieron",
    },
  },
  {
    infinitive: "beber",
    english: "to drink",
    type: "er",
    present: {
      yo: "bebo",
      tu: "bebes",
      el: "bebe",
      nosotros: "bebemos",
      ellos: "beben",
    },
    preterite: {
      yo: "bebí",
      tu: "bebiste",
      el: "bebió",
      nosotros: "bebimos",
      ellos: "bebieron",
    },
  },
  {
    infinitive: "leer",
    english: "to read",
    type: "er",
    present: {
      yo: "leo",
      tu: "lees",
      el: "lee",
      nosotros: "leemos",
      ellos: "leen",
    },
    preterite: {
      yo: "leí",
      tu: "leíste",
      el: "leyó",
      nosotros: "leímos",
      ellos: "leyeron",
    },
  },
  // Regular -IR verbs
  {
    infinitive: "vivir",
    english: "to live",
    type: "ir",
    present: {
      yo: "vivo",
      tu: "vives",
      el: "vive",
      nosotros: "vivimos",
      ellos: "viven",
    },
    preterite: {
      yo: "viví",
      tu: "viviste",
      el: "vivió",
      nosotros: "vivimos",
      ellos: "vivieron",
    },
  },
  {
    infinitive: "escribir",
    english: "to write",
    type: "ir",
    present: {
      yo: "escribo",
      tu: "escribes",
      el: "escribe",
      nosotros: "escribimos",
      ellos: "escriben",
    },
    preterite: {
      yo: "escribí",
      tu: "escribiste",
      el: "escribió",
      nosotros: "escribimos",
      ellos: "escribieron",
    },
  },
  // Irregular verbs
  {
    infinitive: "ser",
    english: "to be (permanent)",
    type: "irregular",
    present: {
      yo: "soy",
      tu: "eres",
      el: "es",
      nosotros: "somos",
      ellos: "son",
    },
    preterite: {
      yo: "fui",
      tu: "fuiste",
      el: "fue",
      nosotros: "fuimos",
      ellos: "fueron",
    },
    irregularNote: "Completely irregular in all forms",
  },
  {
    infinitive: "estar",
    english: "to be (temporary)",
    type: "irregular",
    present: {
      yo: "estoy",
      tu: "estás",
      el: "está",
      nosotros: "estamos",
      ellos: "están",
    },
    preterite: {
      yo: "estuve",
      tu: "estuviste",
      el: "estuvo",
      nosotros: "estuvimos",
      ellos: "estuvieron",
    },
    irregularNote: "Irregular yo form in present; stem change in preterite",
  },
  {
    infinitive: "ir",
    english: "to go",
    type: "irregular",
    present: {
      yo: "voy",
      tu: "vas",
      el: "va",
      nosotros: "vamos",
      ellos: "van",
    },
    preterite: {
      yo: "fui",
      tu: "fuiste",
      el: "fue",
      nosotros: "fuimos",
      ellos: "fueron",
    },
    irregularNote: "Completely irregular; same preterite as 'ser'",
  },
  {
    infinitive: "tener",
    english: "to have",
    type: "irregular",
    present: {
      yo: "tengo",
      tu: "tienes",
      el: "tiene",
      nosotros: "tenemos",
      ellos: "tienen",
    },
    preterite: {
      yo: "tuve",
      tu: "tuviste",
      el: "tuvo",
      nosotros: "tuvimos",
      ellos: "tuvieron",
    },
    irregularNote: "e→ie stem change; irregular yo form",
  },
  {
    infinitive: "hacer",
    english: "to do/make",
    type: "irregular",
    present: {
      yo: "hago",
      tu: "haces",
      el: "hace",
      nosotros: "hacemos",
      ellos: "hacen",
    },
    preterite: {
      yo: "hice",
      tu: "hiciste",
      el: "hizo",
      nosotros: "hicimos",
      ellos: "hicieron",
    },
    irregularNote: "Irregular yo form; c→z in third person preterite",
  },
  {
    infinitive: "querer",
    english: "to want/love",
    type: "irregular",
    present: {
      yo: "quiero",
      tu: "quieres",
      el: "quiere",
      nosotros: "queremos",
      ellos: "quieren",
    },
    preterite: {
      yo: "quise",
      tu: "quisiste",
      el: "quiso",
      nosotros: "quisimos",
      ellos: "quisieron",
    },
    irregularNote: "e→ie stem change in present",
  },
  {
    infinitive: "poder",
    english: "to be able/can",
    type: "irregular",
    present: {
      yo: "puedo",
      tu: "puedes",
      el: "puede",
      nosotros: "podemos",
      ellos: "pueden",
    },
    preterite: {
      yo: "pude",
      tu: "pudiste",
      el: "pudo",
      nosotros: "pudimos",
      ellos: "pudieron",
    },
    irregularNote: "o→ue stem change in present",
  },
  {
    infinitive: "venir",
    english: "to come",
    type: "irregular",
    present: {
      yo: "vengo",
      tu: "vienes",
      el: "viene",
      nosotros: "venimos",
      ellos: "vienen",
    },
    preterite: {
      yo: "vine",
      tu: "viniste",
      el: "vino",
      nosotros: "vinimos",
      ellos: "vinieron",
    },
    irregularNote: "e→ie stem change; irregular yo form",
  },
  {
    infinitive: "saber",
    english: "to know (facts)",
    type: "irregular",
    present: {
      yo: "sé",
      tu: "sabes",
      el: "sabe",
      nosotros: "sabemos",
      ellos: "saben",
    },
    preterite: {
      yo: "supe",
      tu: "supiste",
      el: "supo",
      nosotros: "supimos",
      ellos: "supieron",
    },
    irregularNote: "Irregular yo form in present",
  },
  {
    infinitive: "conocer",
    english: "to know (people)",
    type: "irregular",
    present: {
      yo: "conozco",
      tu: "conoces",
      el: "conoce",
      nosotros: "conocemos",
      ellos: "conocen",
    },
    preterite: {
      yo: "conocí",
      tu: "conociste",
      el: "conoció",
      nosotros: "conocimos",
      ellos: "conocieron",
    },
    irregularNote: "c→zc in yo form (present)",
  },
];

export const commonVerbsVocabulary = {
  id: "spanish-vocab-verbs",
  title: "Common Verbs",
  description: "Essential Spanish verbs for everyday communication",
  cards: commonVerbCards,
  difficulty: "beginner" as const,
  cardCount: commonVerbCards.length,
};

/**
 * Get verbs by type for the verb game
 */
export function getVerbsByType(types: ("ar" | "er" | "ir" | "irregular")[]): SpanishVerbConjugation[] {
  return verbConjugations.filter((v) => types.includes(v.type));
}

/**
 * Check if a conjugation answer is correct (handles accents)
 */
export function checkConjugation(expected: string, userAnswer: string): boolean {
  const normalize = (str: string) =>
    str
      .toLowerCase()
      .trim()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "");

  return normalize(expected) === normalize(userAnswer);
}
