import type { SpanishVocabularyCard } from "@/types/activity";

export const everydayPhrasesCards: SpanishVocabularyCard[] = [
  // Restaurant & Ordering
  {
    id: "mesa-para",
    spanish: "Una mesa para dos, por favor",
    english: "A table for two, please",
    pronunciation: "OO-nah MEH-sah PAH-rah dohs, pohr fah-BOHR",
    example: { spanish: "Buenas noches. Una mesa para dos, por favor.", english: "Good evening. A table for two, please." },
    gender: null,
    difficulty: "beginner",
    category: "restaurant",
  },
  {
    id: "el-menu",
    spanish: "¿Me puede traer el menú?",
    english: "Can you bring me the menu?",
    pronunciation: "meh PWEH-deh trah-EHR ehl meh-NOO",
    example: { spanish: "Disculpe, ¿me puede traer el menú?", english: "Excuse me, can you bring me the menu?" },
    gender: null,
    difficulty: "beginner",
    category: "restaurant",
  },
  {
    id: "que-recomienda",
    spanish: "¿Qué me recomienda?",
    english: "What do you recommend?",
    pronunciation: "keh meh reh-koh-MYEHN-dah",
    example: { spanish: "Es mi primera vez aquí. ¿Qué me recomienda?", english: "It's my first time here. What do you recommend?" },
    gender: null,
    difficulty: "beginner",
    category: "restaurant",
  },
  {
    id: "para-mi",
    spanish: "Para mí...",
    english: "For me... / I'll have...",
    pronunciation: "PAH-rah mee",
    example: { spanish: "Para mí, el pollo con arroz.", english: "For me, the chicken with rice." },
    gender: null,
    difficulty: "beginner",
    category: "restaurant",
  },
  {
    id: "la-cuenta",
    spanish: "La cuenta, por favor",
    english: "The check, please",
    pronunciation: "lah KWEHN-tah, pohr fah-BOHR",
    example: { spanish: "Estamos listos. La cuenta, por favor.", english: "We're ready. The check, please." },
    gender: null,
    difficulty: "beginner",
    category: "restaurant",
  },
  {
    id: "esta-incluida-propina",
    spanish: "¿Está incluida la propina?",
    english: "Is the tip included?",
    pronunciation: "ehs-TAH een-kloo-EE-dah lah proh-PEE-nah",
    example: { spanish: "Disculpe, ¿está incluida la propina?", english: "Excuse me, is the tip included?" },
    gender: null,
    difficulty: "intermediate",
    category: "restaurant",
  },
  {
    id: "muy-rico",
    spanish: "¡Muy rico!",
    english: "Very delicious!",
    pronunciation: "mwee REE-koh",
    example: { spanish: "La comida estuvo muy rica, gracias.", english: "The food was very delicious, thank you." },
    gender: null,
    difficulty: "beginner",
    category: "restaurant",
  },

  // Shopping & Market
  {
    id: "cuanto-cuesta",
    spanish: "¿Cuánto cuesta?",
    english: "How much does it cost?",
    pronunciation: "KWAHN-toh KWEHS-tah",
    example: { spanish: "Me gusta esta camisa. ¿Cuánto cuesta?", english: "I like this shirt. How much does it cost?" },
    gender: null,
    difficulty: "beginner",
    category: "shopping",
  },
  {
    id: "cuanto-cuestan",
    spanish: "¿Cuánto cuestan?",
    english: "How much do they cost?",
    pronunciation: "KWAHN-toh KWEHS-tahn",
    example: { spanish: "¿Cuánto cuestan los mangos?", english: "How much do the mangos cost?" },
    gender: null,
    difficulty: "beginner",
    category: "shopping",
  },
  {
    id: "me-lo-llevo",
    spanish: "Me lo llevo",
    english: "I'll take it",
    pronunciation: "meh loh YEH-boh",
    example: { spanish: "Está perfecto. Me lo llevo.", english: "It's perfect. I'll take it." },
    gender: null,
    difficulty: "beginner",
    category: "shopping",
  },
  {
    id: "solo-estoy-viendo",
    spanish: "Solo estoy viendo",
    english: "I'm just looking",
    pronunciation: "SOH-loh ehs-TOY BYEHN-doh",
    example: { spanish: "Gracias, solo estoy viendo.", english: "Thank you, I'm just looking." },
    gender: null,
    difficulty: "beginner",
    category: "shopping",
  },
  {
    id: "tiene-otro-color",
    spanish: "¿Tiene en otro color?",
    english: "Do you have it in another color?",
    pronunciation: "TYEH-neh ehn OH-troh koh-LOHR",
    example: { spanish: "Me gusta, pero ¿tiene en otro color?", english: "I like it, but do you have it in another color?" },
    gender: null,
    difficulty: "intermediate",
    category: "shopping",
  },
  {
    id: "tiene-mas-grande",
    spanish: "¿Tiene más grande?",
    english: "Do you have a bigger one?",
    pronunciation: "TYEH-neh mahs GRAHN-deh",
    example: { spanish: "Me queda pequeño. ¿Tiene más grande?", english: "It's too small for me. Do you have a bigger one?" },
    gender: null,
    difficulty: "intermediate",
    category: "shopping",
  },
  {
    id: "aceptan-tarjeta",
    spanish: "¿Aceptan tarjeta?",
    english: "Do you accept cards?",
    pronunciation: "ah-SEHP-tahn tahr-HEH-tah",
    example: { spanish: "¿Aceptan tarjeta o solo efectivo?", english: "Do you accept cards or only cash?" },
    gender: null,
    difficulty: "beginner",
    category: "shopping",
  },
  {
    id: "solo-efectivo",
    spanish: "Solo efectivo",
    english: "Cash only",
    pronunciation: "SOH-loh eh-fehk-TEE-boh",
    example: { spanish: "Lo siento, solo efectivo.", english: "Sorry, cash only." },
    gender: null,
    difficulty: "beginner",
    category: "shopping",
  },

  // Directions & Transportation
  {
    id: "donde-esta",
    spanish: "¿Dónde está...?",
    english: "Where is...?",
    pronunciation: "DOHN-deh ehs-TAH",
    example: { spanish: "Perdón, ¿dónde está el mercado?", english: "Excuse me, where is the market?" },
    gender: null,
    difficulty: "beginner",
    category: "directions",
  },
  {
    id: "como-llego",
    spanish: "¿Cómo llego a...?",
    english: "How do I get to...?",
    pronunciation: "KOH-moh YEH-goh ah",
    example: { spanish: "¿Cómo llego a la estación de bus?", english: "How do I get to the bus station?" },
    gender: null,
    difficulty: "beginner",
    category: "directions",
  },
  {
    id: "esta-lejos",
    spanish: "¿Está lejos?",
    english: "Is it far?",
    pronunciation: "ehs-TAH LEH-hohs",
    example: { spanish: "¿Está lejos o puedo ir caminando?", english: "Is it far or can I walk there?" },
    gender: null,
    difficulty: "beginner",
    category: "directions",
  },
  {
    id: "esta-cerca",
    spanish: "Está cerca",
    english: "It's close / nearby",
    pronunciation: "ehs-TAH SEHR-kah",
    example: { spanish: "Sí, está cerca. A dos cuadras.", english: "Yes, it's close. Two blocks away." },
    gender: null,
    difficulty: "beginner",
    category: "directions",
  },
  {
    id: "a-la-derecha",
    spanish: "A la derecha",
    english: "To the right",
    pronunciation: "ah lah deh-REH-chah",
    example: { spanish: "Siga derecho y luego a la derecha.", english: "Go straight and then to the right." },
    gender: null,
    difficulty: "beginner",
    category: "directions",
  },
  {
    id: "a-la-izquierda",
    spanish: "A la izquierda",
    english: "To the left",
    pronunciation: "ah lah ees-KYEHR-dah",
    example: { spanish: "El banco está a la izquierda.", english: "The bank is to the left." },
    gender: null,
    difficulty: "beginner",
    category: "directions",
  },
  {
    id: "siga-derecho",
    spanish: "Siga derecho",
    english: "Go straight",
    pronunciation: "SEE-gah deh-REH-choh",
    example: { spanish: "Siga derecho por dos cuadras.", english: "Go straight for two blocks." },
    gender: null,
    difficulty: "beginner",
    category: "directions",
  },
  {
    id: "cuanto-tarda",
    spanish: "¿Cuánto tarda?",
    english: "How long does it take?",
    pronunciation: "KWAHN-toh TAHR-dah",
    example: { spanish: "¿Cuánto tarda el bus a San José?", english: "How long does the bus to San José take?" },
    gender: null,
    difficulty: "intermediate",
    category: "transportation",
  },
  {
    id: "a-que-hora-sale",
    spanish: "¿A qué hora sale?",
    english: "What time does it leave?",
    pronunciation: "ah keh OH-rah SAH-leh",
    example: { spanish: "¿A qué hora sale el próximo bus?", english: "What time does the next bus leave?" },
    gender: null,
    difficulty: "intermediate",
    category: "transportation",
  },
  {
    id: "un-boleto-a",
    spanish: "Un boleto a...",
    english: "A ticket to...",
    pronunciation: "oon boh-LEH-toh ah",
    example: { spanish: "Un boleto a Antigua, por favor.", english: "A ticket to Antigua, please." },
    gender: "masculine",
    difficulty: "beginner",
    category: "transportation",
  },

  // General Communication
  {
    id: "no-entiendo",
    spanish: "No entiendo",
    english: "I don't understand",
    pronunciation: "noh ehn-TYEHN-doh",
    example: { spanish: "Lo siento, no entiendo. ¿Puede repetir?", english: "I'm sorry, I don't understand. Can you repeat?" },
    gender: null,
    difficulty: "beginner",
    category: "communication",
  },
  {
    id: "puede-repetir",
    spanish: "¿Puede repetir, por favor?",
    english: "Can you repeat, please?",
    pronunciation: "PWEH-deh reh-peh-TEER pohr fah-BOHR",
    example: { spanish: "Habla muy rápido. ¿Puede repetir?", english: "You speak very fast. Can you repeat?" },
    gender: null,
    difficulty: "beginner",
    category: "communication",
  },
  {
    id: "mas-despacio",
    spanish: "Más despacio, por favor",
    english: "More slowly, please",
    pronunciation: "mahs dehs-PAH-syoh pohr fah-BOHR",
    example: { spanish: "¿Puede hablar más despacio, por favor?", english: "Can you speak more slowly, please?" },
    gender: null,
    difficulty: "beginner",
    category: "communication",
  },
  {
    id: "como-se-dice",
    spanish: "¿Cómo se dice...?",
    english: "How do you say...?",
    pronunciation: "KOH-moh seh DEE-seh",
    example: { spanish: "¿Cómo se dice 'apple' en español?", english: "How do you say 'apple' in Spanish?" },
    gender: null,
    difficulty: "beginner",
    category: "communication",
  },
  {
    id: "que-significa",
    spanish: "¿Qué significa...?",
    english: "What does... mean?",
    pronunciation: "keh seeg-NEE-fee-kah",
    example: { spanish: "¿Qué significa 'chévere'?", english: "What does 'chévere' mean?" },
    gender: null,
    difficulty: "beginner",
    category: "communication",
  },
  {
    id: "hablo-poco-espanol",
    spanish: "Hablo poco español",
    english: "I speak a little Spanish",
    pronunciation: "AH-bloh POH-koh ehs-pah-NYOHL",
    example: { spanish: "Hablo poco español, pero estoy aprendiendo.", english: "I speak a little Spanish, but I'm learning." },
    gender: null,
    difficulty: "beginner",
    category: "communication",
  },
  {
    id: "estoy-aprendiendo",
    spanish: "Estoy aprendiendo español",
    english: "I'm learning Spanish",
    pronunciation: "ehs-TOY ah-prehn-DYEHN-doh ehs-pah-NYOHL",
    example: { spanish: "Estoy aprendiendo español. ¿Me puede ayudar?", english: "I'm learning Spanish. Can you help me?" },
    gender: null,
    difficulty: "beginner",
    category: "communication",
  },

  // Everyday Needs
  {
    id: "necesito",
    spanish: "Necesito...",
    english: "I need...",
    pronunciation: "neh-seh-SEE-toh",
    example: { spanish: "Necesito un taxi.", english: "I need a taxi." },
    gender: null,
    difficulty: "beginner",
    category: "needs",
  },
  {
    id: "busco",
    spanish: "Busco...",
    english: "I'm looking for...",
    pronunciation: "BOOS-koh",
    example: { spanish: "Busco una farmacia.", english: "I'm looking for a pharmacy." },
    gender: null,
    difficulty: "beginner",
    category: "needs",
  },
  {
    id: "hay-wifi",
    spanish: "¿Hay wifi?",
    english: "Is there wifi?",
    pronunciation: "eye WEE-fee",
    example: { spanish: "¿Hay wifi aquí? ¿Cuál es la contraseña?", english: "Is there wifi here? What's the password?" },
    gender: null,
    difficulty: "beginner",
    category: "needs",
  },
  {
    id: "donde-esta-bano",
    spanish: "¿Dónde está el baño?",
    english: "Where is the bathroom?",
    pronunciation: "DOHN-deh ehs-TAH ehl BAH-nyoh",
    example: { spanish: "Disculpe, ¿dónde está el baño?", english: "Excuse me, where is the bathroom?" },
    gender: null,
    difficulty: "beginner",
    category: "needs",
  },
  {
    id: "puedo-usar",
    spanish: "¿Puedo usar...?",
    english: "Can I use...?",
    pronunciation: "PWEH-doh oo-SAHR",
    example: { spanish: "¿Puedo usar su teléfono?", english: "Can I use your phone?" },
    gender: null,
    difficulty: "beginner",
    category: "needs",
  },
  {
    id: "tiene-agua",
    spanish: "¿Tiene agua?",
    english: "Do you have water?",
    pronunciation: "TYEH-neh AH-gwah",
    example: { spanish: "¿Tiene agua, por favor?", english: "Do you have water, please?" },
    gender: null,
    difficulty: "beginner",
    category: "needs",
  },

  // Social & Politeness (Latin American style)
  {
    id: "con-permiso",
    spanish: "Con permiso",
    english: "Excuse me (to pass by)",
    pronunciation: "kohn pehr-MEE-soh",
    example: { spanish: "Con permiso, necesito pasar.", english: "Excuse me, I need to get through." },
    gender: null,
    difficulty: "beginner",
    category: "courtesy",
  },
  {
    id: "disculpe",
    spanish: "Disculpe",
    english: "Excuse me (formal) / Sorry",
    pronunciation: "dees-KOOL-peh",
    example: { spanish: "Disculpe, ¿tiene la hora?", english: "Excuse me, do you have the time?" },
    gender: null,
    difficulty: "beginner",
    category: "courtesy",
  },
  {
    id: "con-mucho-gusto",
    spanish: "Con mucho gusto",
    english: "With pleasure / You're welcome",
    pronunciation: "kohn MOO-choh GOO-stoh",
    example: { spanish: "—Gracias por su ayuda. —Con mucho gusto.", english: "—Thank you for your help. —With pleasure." },
    gender: null,
    difficulty: "beginner",
    category: "courtesy",
  },
  {
    id: "que-le-vaya-bien",
    spanish: "¡Que le vaya bien!",
    english: "Take care! / Have a good one!",
    pronunciation: "keh leh BAH-yah byehn",
    example: { spanish: "Adiós, ¡que le vaya bien!", english: "Goodbye, take care!" },
    gender: null,
    difficulty: "intermediate",
    category: "courtesy",
  },
  {
    id: "igualmente",
    spanish: "Igualmente",
    english: "Likewise / Same to you",
    pronunciation: "ee-gwahl-MEHN-teh",
    example: { spanish: "—¡Buen provecho! —Igualmente.", english: "—Enjoy your meal! —Same to you." },
    gender: null,
    difficulty: "beginner",
    category: "courtesy",
  },
  {
    id: "buen-provecho",
    spanish: "¡Buen provecho!",
    english: "Enjoy your meal!",
    pronunciation: "bwehn proh-BEH-choh",
    example: { spanish: "Aquí está su comida. ¡Buen provecho!", english: "Here's your food. Enjoy your meal!" },
    gender: null,
    difficulty: "beginner",
    category: "courtesy",
  },
];

export const everydayPhrasesVocabulary = {
  id: "spanish-vocab-everyday",
  title: "Everyday Phrases",
  description: "Essential conversational phrases for restaurants, shopping, directions, and daily life in Latin America",
  cards: everydayPhrasesCards,
  difficulty: "beginner" as const,
  cardCount: everydayPhrasesCards.length,
};
