import type { SpanishVocabularyCard } from "@/types/activity";

export const familyRelationshipsCards: SpanishVocabularyCard[] = [
  {
    id: "familia",
    spanish: "la familia",
    english: "the family",
    pronunciation: "fah-MEE-lyah",
    example: { spanish: "Mi familia es grande.", english: "My family is big." },
    gender: "feminine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "madre",
    spanish: "la madre",
    english: "the mother",
    pronunciation: "MAH-dreh",
    example: { spanish: "Mi madre cocina bien.", english: "My mother cooks well." },
    gender: "feminine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "padre",
    spanish: "el padre",
    english: "the father",
    pronunciation: "PAH-dreh",
    example: { spanish: "Mi padre trabaja mucho.", english: "My father works a lot." },
    gender: "masculine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "padres",
    spanish: "los padres",
    english: "the parents",
    pronunciation: "PAH-drehs",
    example: { spanish: "Mis padres viven en España.", english: "My parents live in Spain." },
    gender: "masculine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "hermano",
    spanish: "el hermano",
    english: "the brother",
    pronunciation: "ehr-MAH-noh",
    example: { spanish: "Mi hermano es alto.", english: "My brother is tall." },
    gender: "masculine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "hermana",
    spanish: "la hermana",
    english: "the sister",
    pronunciation: "ehr-MAH-nah",
    example: { spanish: "Mi hermana estudia medicina.", english: "My sister studies medicine." },
    gender: "feminine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "hijo",
    spanish: "el hijo",
    english: "the son",
    pronunciation: "EE-hoh",
    example: { spanish: "Su hijo tiene tres años.", english: "Her son is three years old." },
    gender: "masculine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "hija",
    spanish: "la hija",
    english: "the daughter",
    pronunciation: "EE-hah",
    example: { spanish: "Mi hija va a la escuela.", english: "My daughter goes to school." },
    gender: "feminine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "abuelo",
    spanish: "el abuelo",
    english: "the grandfather",
    pronunciation: "ah-BWEH-loh",
    example: { spanish: "Mi abuelo cuenta historias.", english: "My grandfather tells stories." },
    gender: "masculine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "abuela",
    spanish: "la abuela",
    english: "the grandmother",
    pronunciation: "ah-BWEH-lah",
    example: { spanish: "Mi abuela hace el mejor pastel.", english: "My grandmother makes the best cake." },
    gender: "feminine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "tio",
    spanish: "el tío",
    english: "the uncle",
    pronunciation: "TEE-oh",
    example: { spanish: "Mi tío vive en México.", english: "My uncle lives in Mexico." },
    gender: "masculine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "tia",
    spanish: "la tía",
    english: "the aunt",
    pronunciation: "TEE-ah",
    example: { spanish: "Mi tía es doctora.", english: "My aunt is a doctor." },
    gender: "feminine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "primo",
    spanish: "el primo",
    english: "the cousin (male)",
    pronunciation: "PREE-moh",
    example: { spanish: "Mi primo juega fútbol.", english: "My cousin plays soccer." },
    gender: "masculine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "prima",
    spanish: "la prima",
    english: "the cousin (female)",
    pronunciation: "PREE-mah",
    example: { spanish: "Mi prima vive cerca.", english: "My cousin lives nearby." },
    gender: "feminine",
    difficulty: "beginner",
    category: "family",
  },
  {
    id: "esposo",
    spanish: "el esposo",
    english: "the husband",
    pronunciation: "ehs-POH-soh",
    example: { spanish: "Su esposo es muy amable.", english: "Her husband is very kind." },
    gender: "masculine",
    difficulty: "intermediate",
    category: "family",
  },
  {
    id: "esposa",
    spanish: "la esposa",
    english: "the wife",
    pronunciation: "ehs-POH-sah",
    example: { spanish: "Mi esposa trabaja en un banco.", english: "My wife works at a bank." },
    gender: "feminine",
    difficulty: "intermediate",
    category: "family",
  },
];

export const familyRelationshipsVocabulary = {
  id: "spanish-vocab-family",
  title: "Family & Relationships",
  description: "Learn family members and relationships in Spanish",
  cards: familyRelationshipsCards,
  difficulty: "beginner" as const,
  cardCount: familyRelationshipsCards.length,
};
