import type { SpanishVocabularyCard } from "@/types/activity";

export const greetingsBasicsCards: SpanishVocabularyCard[] = [
  {
    id: "hola",
    spanish: "Hola",
    english: "Hello",
    pronunciation: "OH-lah",
    example: { spanish: "¡Hola! ¿Cómo estás?", english: "Hello! How are you?" },
    gender: null,
    difficulty: "beginner",
    category: "greetings",
  },
  {
    id: "buenos-dias",
    spanish: "Buenos días",
    english: "Good morning",
    pronunciation: "BWEH-nohs DEE-ahs",
    example: { spanish: "Buenos días, señora.", english: "Good morning, ma'am." },
    gender: null,
    difficulty: "beginner",
    category: "greetings",
  },
  {
    id: "buenas-tardes",
    spanish: "Buenas tardes",
    english: "Good afternoon",
    pronunciation: "BWEH-nahs TAR-dehs",
    example: { spanish: "Buenas tardes, ¿cómo le va?", english: "Good afternoon, how are you doing?" },
    gender: null,
    difficulty: "beginner",
    category: "greetings",
  },
  {
    id: "buenas-noches",
    spanish: "Buenas noches",
    english: "Good evening / Good night",
    pronunciation: "BWEH-nahs NOH-chehs",
    example: { spanish: "Buenas noches, hasta mañana.", english: "Good night, see you tomorrow." },
    gender: null,
    difficulty: "beginner",
    category: "greetings",
  },
  {
    id: "adios",
    spanish: "Adiós",
    english: "Goodbye",
    pronunciation: "ah-DYOHS",
    example: { spanish: "Adiós, nos vemos pronto.", english: "Goodbye, see you soon." },
    gender: null,
    difficulty: "beginner",
    category: "greetings",
  },
  {
    id: "hasta-luego",
    spanish: "Hasta luego",
    english: "See you later",
    pronunciation: "AH-stah LWEH-goh",
    example: { spanish: "Me voy, hasta luego.", english: "I'm leaving, see you later." },
    gender: null,
    difficulty: "beginner",
    category: "greetings",
  },
  {
    id: "hasta-manana",
    spanish: "Hasta mañana",
    english: "See you tomorrow",
    pronunciation: "AH-stah mah-NYAH-nah",
    example: { spanish: "Buenas noches, hasta mañana.", english: "Good night, see you tomorrow." },
    gender: null,
    difficulty: "beginner",
    category: "greetings",
  },
  {
    id: "como-estas",
    spanish: "¿Cómo estás?",
    english: "How are you? (informal)",
    pronunciation: "KOH-moh ehs-TAHS",
    example: { spanish: "Hola, ¿cómo estás hoy?", english: "Hi, how are you today?" },
    gender: null,
    difficulty: "beginner",
    category: "greetings",
  },
  {
    id: "muy-bien",
    spanish: "Muy bien",
    english: "Very well",
    pronunciation: "mwee byehn",
    example: { spanish: "Estoy muy bien, gracias.", english: "I'm very well, thank you." },
    gender: null,
    difficulty: "beginner",
    category: "responses",
  },
  {
    id: "gracias",
    spanish: "Gracias",
    english: "Thank you",
    pronunciation: "GRAH-syahs",
    example: { spanish: "Muchas gracias por tu ayuda.", english: "Thank you very much for your help." },
    gender: null,
    difficulty: "beginner",
    category: "courtesy",
  },
  {
    id: "de-nada",
    spanish: "De nada",
    english: "You're welcome",
    pronunciation: "deh NAH-dah",
    example: { spanish: "—Gracias. —De nada.", english: "—Thank you. —You're welcome." },
    gender: null,
    difficulty: "beginner",
    category: "courtesy",
  },
  {
    id: "por-favor",
    spanish: "Por favor",
    english: "Please",
    pronunciation: "pohr fah-BOHR",
    example: { spanish: "Un café, por favor.", english: "A coffee, please." },
    gender: null,
    difficulty: "beginner",
    category: "courtesy",
  },
  {
    id: "lo-siento",
    spanish: "Lo siento",
    english: "I'm sorry",
    pronunciation: "loh SYEHN-toh",
    example: { spanish: "Lo siento, llegué tarde.", english: "I'm sorry, I arrived late." },
    gender: null,
    difficulty: "beginner",
    category: "courtesy",
  },
  {
    id: "perdon",
    spanish: "Perdón",
    english: "Excuse me / Pardon",
    pronunciation: "pehr-DOHN",
    example: { spanish: "Perdón, ¿dónde está el baño?", english: "Excuse me, where is the bathroom?" },
    gender: null,
    difficulty: "beginner",
    category: "courtesy",
  },
  {
    id: "si",
    spanish: "Sí",
    english: "Yes",
    pronunciation: "see",
    example: { spanish: "Sí, entiendo.", english: "Yes, I understand." },
    gender: null,
    difficulty: "beginner",
    category: "basics",
  },
  {
    id: "no",
    spanish: "No",
    english: "No",
    pronunciation: "noh",
    example: { spanish: "No, gracias.", english: "No, thank you." },
    gender: null,
    difficulty: "beginner",
    category: "basics",
  },
  {
    id: "me-llamo",
    spanish: "Me llamo...",
    english: "My name is...",
    pronunciation: "meh YAH-moh",
    example: { spanish: "Me llamo María.", english: "My name is María." },
    gender: null,
    difficulty: "beginner",
    category: "introductions",
  },
  {
    id: "mucho-gusto",
    spanish: "Mucho gusto",
    english: "Nice to meet you",
    pronunciation: "MOO-choh GOO-stoh",
    example: { spanish: "Mucho gusto, soy Juan.", english: "Nice to meet you, I'm Juan." },
    gender: null,
    difficulty: "beginner",
    category: "introductions",
  },
  {
    id: "como-te-llamas",
    spanish: "¿Cómo te llamas?",
    english: "What's your name? (informal)",
    pronunciation: "KOH-moh teh YAH-mahs",
    example: { spanish: "Hola, ¿cómo te llamas?", english: "Hello, what's your name?" },
    gender: null,
    difficulty: "beginner",
    category: "introductions",
  },
  {
    id: "encantado",
    spanish: "Encantado/a",
    english: "Pleased to meet you",
    pronunciation: "ehn-kahn-TAH-doh",
    example: { spanish: "Encantada de conocerte.", english: "Pleased to meet you." },
    gender: null,
    difficulty: "beginner",
    category: "introductions",
  },
];

export const greetingsBasicsVocabulary = {
  id: "spanish-vocab-greetings",
  title: "Greetings & Basics",
  description: "Essential Spanish greetings, introductions, and polite expressions",
  cards: greetingsBasicsCards,
  difficulty: "beginner" as const,
  cardCount: greetingsBasicsCards.length,
};
