import type { SpanishVocabularyCard } from "@/types/activity";

export const numbers1to100Cards: SpanishVocabularyCard[] = [
  // 0-10
  {
    id: "cero",
    spanish: "cero",
    english: "zero",
    pronunciation: "SEH-roh",
    example: { spanish: "El resultado es cero.", english: "The result is zero." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "uno",
    spanish: "uno",
    english: "one",
    pronunciation: "OO-noh",
    example: { spanish: "Tengo un hermano.", english: "I have one brother." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "dos",
    spanish: "dos",
    english: "two",
    pronunciation: "dohs",
    example: { spanish: "Hay dos gatos.", english: "There are two cats." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "tres",
    spanish: "tres",
    english: "three",
    pronunciation: "trehs",
    example: { spanish: "Tres amigos.", english: "Three friends." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "cuatro",
    spanish: "cuatro",
    english: "four",
    pronunciation: "KWAH-troh",
    example: { spanish: "Cuatro estaciones del año.", english: "Four seasons of the year." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "cinco",
    spanish: "cinco",
    english: "five",
    pronunciation: "SEEN-koh",
    example: { spanish: "Tengo cinco dedos.", english: "I have five fingers." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "seis",
    spanish: "seis",
    english: "six",
    pronunciation: "says",
    example: { spanish: "Son las seis.", english: "It's six o'clock." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "siete",
    spanish: "siete",
    english: "seven",
    pronunciation: "SYEH-teh",
    example: { spanish: "Siete días de la semana.", english: "Seven days of the week." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "ocho",
    spanish: "ocho",
    english: "eight",
    pronunciation: "OH-choh",
    example: { spanish: "Ocho horas de sueño.", english: "Eight hours of sleep." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "nueve",
    spanish: "nueve",
    english: "nine",
    pronunciation: "NWEH-beh",
    example: { spanish: "Nueve planetas... bueno, ocho.", english: "Nine planets... well, eight." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "diez",
    spanish: "diez",
    english: "ten",
    pronunciation: "dyehs",
    example: { spanish: "Diez minutos.", english: "Ten minutes." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  // 11-20
  {
    id: "once",
    spanish: "once",
    english: "eleven",
    pronunciation: "OHN-seh",
    example: { spanish: "El equipo tiene once jugadores.", english: "The team has eleven players." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "doce",
    spanish: "doce",
    english: "twelve",
    pronunciation: "DOH-seh",
    example: { spanish: "Doce meses del año.", english: "Twelve months of the year." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "trece",
    spanish: "trece",
    english: "thirteen",
    pronunciation: "TREH-seh",
    example: { spanish: "Viernes trece.", english: "Friday the thirteenth." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "catorce",
    spanish: "catorce",
    english: "fourteen",
    pronunciation: "kah-TOHR-seh",
    example: { spanish: "Tiene catorce años.", english: "He/She is fourteen years old." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "quince",
    spanish: "quince",
    english: "fifteen",
    pronunciation: "KEEN-seh",
    example: { spanish: "Quinceañera a los quince.", english: "Quinceañera at fifteen." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "dieciseis",
    spanish: "dieciséis",
    english: "sixteen",
    pronunciation: "dyeh-see-SAYS",
    example: { spanish: "Dieciséis velas en el pastel.", english: "Sixteen candles on the cake." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "diecisiete",
    spanish: "diecisiete",
    english: "seventeen",
    pronunciation: "dyeh-see-SYEH-teh",
    example: { spanish: "Diecisiete estudiantes.", english: "Seventeen students." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "dieciocho",
    spanish: "dieciocho",
    english: "eighteen",
    pronunciation: "dyeh-see-OH-choh",
    example: { spanish: "A los dieciocho eres adulto.", english: "At eighteen you're an adult." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "diecinueve",
    spanish: "diecinueve",
    english: "nineteen",
    pronunciation: "dyeh-see-NWEH-beh",
    example: { spanish: "Diecinueve puntos.", english: "Nineteen points." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "veinte",
    spanish: "veinte",
    english: "twenty",
    pronunciation: "BAYN-teh",
    example: { spanish: "Veinte preguntas.", english: "Twenty questions." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  // Tens
  {
    id: "treinta",
    spanish: "treinta",
    english: "thirty",
    pronunciation: "TRAYN-tah",
    example: { spanish: "Treinta días tiene septiembre.", english: "September has thirty days." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "cuarenta",
    spanish: "cuarenta",
    english: "forty",
    pronunciation: "kwah-REHN-tah",
    example: { spanish: "Cuarenta grados de calor.", english: "Forty degrees of heat." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "cincuenta",
    spanish: "cincuenta",
    english: "fifty",
    pronunciation: "seen-KWEHN-tah",
    example: { spanish: "Cincuenta por ciento.", english: "Fifty percent." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "sesenta",
    spanish: "sesenta",
    english: "sixty",
    pronunciation: "seh-SEHN-tah",
    example: { spanish: "Sesenta segundos.", english: "Sixty seconds." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "setenta",
    spanish: "setenta",
    english: "seventy",
    pronunciation: "seh-TEHN-tah",
    example: { spanish: "Mi abuela tiene setenta años.", english: "My grandmother is seventy years old." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "ochenta",
    spanish: "ochenta",
    english: "eighty",
    pronunciation: "oh-CHEHN-tah",
    example: { spanish: "Los años ochenta.", english: "The eighties." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "noventa",
    spanish: "noventa",
    english: "ninety",
    pronunciation: "noh-BEHN-tah",
    example: { spanish: "Noventa kilómetros por hora.", english: "Ninety kilometers per hour." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  {
    id: "cien",
    spanish: "cien",
    english: "one hundred",
    pronunciation: "syehn",
    example: { spanish: "Cien por ciento seguro.", english: "One hundred percent sure." },
    gender: null,
    difficulty: "beginner",
    category: "numbers",
  },
  // Compound numbers (examples)
  {
    id: "veintiuno",
    spanish: "veintiuno",
    english: "twenty-one",
    pronunciation: "bayn-tee-OO-noh",
    example: { spanish: "Tengo veintiún años.", english: "I am twenty-one years old." },
    gender: null,
    difficulty: "intermediate",
    category: "numbers",
  },
  {
    id: "treinta-y-dos",
    spanish: "treinta y dos",
    english: "thirty-two",
    pronunciation: "TRAYN-tah ee dohs",
    example: { spanish: "Treinta y dos dientes.", english: "Thirty-two teeth." },
    gender: null,
    difficulty: "intermediate",
    category: "numbers",
  },
];

export const numbers1to100Vocabulary = {
  id: "spanish-vocab-numbers",
  title: "Numbers 1-100",
  description: "Spanish numbers from zero to one hundred",
  cards: numbers1to100Cards,
  difficulty: "beginner" as const,
  cardCount: numbers1to100Cards.length,
};

// Spanish number data for the numbers game
export const SPANISH_NUMBERS: Record<number, string[]> = {
  0: ["cero"],
  1: ["uno", "un"],
  2: ["dos"],
  3: ["tres"],
  4: ["cuatro"],
  5: ["cinco"],
  6: ["seis"],
  7: ["siete"],
  8: ["ocho"],
  9: ["nueve"],
  10: ["diez"],
  11: ["once"],
  12: ["doce"],
  13: ["trece"],
  14: ["catorce"],
  15: ["quince"],
  16: ["dieciséis", "dieciseis"],
  17: ["diecisiete"],
  18: ["dieciocho"],
  19: ["diecinueve"],
  20: ["veinte"],
  21: ["veintiuno", "veinte y uno", "veintiún"],
  22: ["veintidós", "veintidos", "veinte y dos"],
  23: ["veintitrés", "veintitres", "veinte y tres"],
  24: ["veinticuatro", "veinte y cuatro"],
  25: ["veinticinco", "veinte y cinco"],
  26: ["veintiséis", "veintiseis", "veinte y seis"],
  27: ["veintisiete", "veinte y siete"],
  28: ["veintiocho", "veinte y ocho"],
  29: ["veintinueve", "veinte y nueve"],
  30: ["treinta"],
  31: ["treinta y uno"],
  32: ["treinta y dos"],
  33: ["treinta y tres"],
  34: ["treinta y cuatro"],
  35: ["treinta y cinco"],
  36: ["treinta y seis"],
  37: ["treinta y siete"],
  38: ["treinta y ocho"],
  39: ["treinta y nueve"],
  40: ["cuarenta"],
  41: ["cuarenta y uno"],
  42: ["cuarenta y dos"],
  43: ["cuarenta y tres"],
  44: ["cuarenta y cuatro"],
  45: ["cuarenta y cinco"],
  46: ["cuarenta y seis"],
  47: ["cuarenta y siete"],
  48: ["cuarenta y ocho"],
  49: ["cuarenta y nueve"],
  50: ["cincuenta"],
  51: ["cincuenta y uno"],
  52: ["cincuenta y dos"],
  53: ["cincuenta y tres"],
  54: ["cincuenta y cuatro"],
  55: ["cincuenta y cinco"],
  56: ["cincuenta y seis"],
  57: ["cincuenta y siete"],
  58: ["cincuenta y ocho"],
  59: ["cincuenta y nueve"],
  60: ["sesenta"],
  61: ["sesenta y uno"],
  62: ["sesenta y dos"],
  63: ["sesenta y tres"],
  64: ["sesenta y cuatro"],
  65: ["sesenta y cinco"],
  66: ["sesenta y seis"],
  67: ["sesenta y siete"],
  68: ["sesenta y ocho"],
  69: ["sesenta y nueve"],
  70: ["setenta"],
  71: ["setenta y uno"],
  72: ["setenta y dos"],
  73: ["setenta y tres"],
  74: ["setenta y cuatro"],
  75: ["setenta y cinco"],
  76: ["setenta y seis"],
  77: ["setenta y siete"],
  78: ["setenta y ocho"],
  79: ["setenta y nueve"],
  80: ["ochenta"],
  81: ["ochenta y uno"],
  82: ["ochenta y dos"],
  83: ["ochenta y tres"],
  84: ["ochenta y cuatro"],
  85: ["ochenta y cinco"],
  86: ["ochenta y seis"],
  87: ["ochenta y siete"],
  88: ["ochenta y ocho"],
  89: ["ochenta y nueve"],
  90: ["noventa"],
  91: ["noventa y uno"],
  92: ["noventa y dos"],
  93: ["noventa y tres"],
  94: ["noventa y cuatro"],
  95: ["noventa y cinco"],
  96: ["noventa y seis"],
  97: ["noventa y siete"],
  98: ["noventa y ocho"],
  99: ["noventa y nueve"],
  100: ["cien", "ciento"],
};

/**
 * Check if a user's answer matches the expected Spanish number
 * Normalizes accents and allows multiple valid forms
 */
export function checkSpanishNumber(num: number, userAnswer: string): boolean {
  const validAnswers = SPANISH_NUMBERS[num];
  if (!validAnswers) return false;

  const normalized = userAnswer
    .toLowerCase()
    .trim()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, ""); // Remove accents for comparison

  return validAnswers.some((valid) => {
    const normalizedValid = valid
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "");
    return normalized === normalizedValid;
  });
}

/**
 * Get the primary Spanish word for a number (for display)
 */
export function getSpanishNumber(num: number): string {
  const answers = SPANISH_NUMBERS[num];
  return answers ? answers[0] : String(num);
}
