import type { SpanishTier } from "./registry";

export type SpanishObjectiveStatus = "existing" | "planned";

export interface SpanishCourseObjective {
  id: string;
  tier: SpanishTier;
  module: string;
  title: string;
  communicativeGoal?: string;
  status: SpanishObjectiveStatus;
  canonicalGuideId?: string;
  practiceActivityIds?: string[];
  communicativeDomain?: string;
  taskType?: "interpretive" | "interpersonal" | "presentational" | "integrated";
  interactionMode?: "solo" | "partner" | "mixed";
  priority?: "core" | "supporting" | "specialized";
  realWorldScenario?: string;
  recommendedFor?: string[];
  /** Vocab/flashcard activities that support this objective. */
  relatedVocabIds?: string[];
  /** Objective IDs this guide recycles (spiral review). */
  recyclesObjectives?: string[];
  prerequisites?: string[];
  notes?: string;
}

/** Canonical roadmap by tier (Basics, Intermediate, Advanced) to prevent overlap and track objectives. */
export const spanishCourseObjectives: SpanishCourseObjective[] = [
  {
    id: "a1-alphabet-pronunciation",
    tier: "basics",
    module: "Foundations",
    title: "Understand names, signs, and spelled information",
    communicativeGoal: "Catch letters, sounds, and spelling when basic information is exchanged aloud.",
    status: "existing",
    canonicalGuideId: "spanish-alphabet-pronunciation-guide",
    communicativeDomain: "foundations",
    taskType: "interpretive",
    interactionMode: "solo",
    priority: "core",
    realWorldScenario: "You hear a name, address, or word spelled out and need to follow it accurately.",
    recommendedFor: ["adult-self-study", "travel", "new-beginners"],
  },
  {
    id: "a1-gender-articles",
    tier: "basics",
    module: "Foundations",
    title: "Identify and refer to everyday objects clearly",
    communicativeGoal: "Choose articles and noun forms that make basic references understandable.",
    status: "existing",
    canonicalGuideId: "spanish-noun-gender-articles-guide",
    communicativeDomain: "daily-life",
    taskType: "presentational",
    interactionMode: "solo",
    priority: "core",
    realWorldScenario: "You label, describe, or ask for familiar objects in class and daily life.",
    recommendedFor: ["adult-self-study", "new-beginners"],
  },
  {
    id: "a1-present-tense-core",
    tier: "basics",
    module: "Verbs",
    title: "Talk about daily routines and current life",
    communicativeGoal: "Describe habits, schedules, and current facts about your life in simple exchanges.",
    status: "existing",
    canonicalGuideId: "spanish-present-tense-guide",
    communicativeDomain: "daily-life",
    taskType: "interpersonal",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You introduce yourself and explain what you do each day.",
    recommendedFor: ["adult-self-study", "travel", "workplace-basics"],
    practiceActivityIds: [
      "spanish-verb-game-present-ar",
      "spanish-verb-game-present-er-ir",
      "spanish-verb-game-present-irregular",
    ],
    relatedVocabIds: ["spanish-vocab-verbs", "spanish-common-verbs-flashcards"],
    recyclesObjectives: ["a1-gender-articles"],
  },
  {
    id: "a1-ser-estar",
    tier: "basics",
    module: "Core grammar distinctions",
    title: "Describe identity, condition, and location accurately",
    communicativeGoal: "Choose the right be-verb when describing who someone is, where they are, and how they feel.",
    status: "existing",
    canonicalGuideId: "spanish-ser-vs-estar-guide",
    communicativeDomain: "daily-life",
    taskType: "presentational",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You need to say where people are, what they are like, and how they are feeling.",
    recommendedFor: ["adult-self-study", "travel"],
  },
  {
    id: "a1-adjective-agreement",
    tier: "basics",
    module: "Core grammar distinctions",
    title: "Describe people and things so your message sounds natural",
    communicativeGoal: "Use matching adjective forms while giving simple descriptions.",
    status: "existing",
    canonicalGuideId: "spanish-adjective-agreement-guide",
    communicativeDomain: "describing-people-and-things",
    taskType: "presentational",
    interactionMode: "solo",
    priority: "core",
    realWorldScenario: "You describe family members, places, and common objects in short exchanges.",
    recommendedFor: ["adult-self-study", "new-beginners"],
  },
  {
    id: "a2-past-tenses",
    tier: "basics",
    module: "Verbs",
    title: "Tell past stories and give background",
    communicativeGoal: "Describe what happened and what the situation was like in the past.",
    status: "existing",
    canonicalGuideId: "spanish-imperfect-tense-guide",
    communicativeDomain: "storytelling",
    taskType: "integrated",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You tell someone about a past trip, incident, or childhood memory.",
    recommendedFor: ["adult-self-study", "travel", "conversation"],
    prerequisites: ["a1-present-tense-core"],
    practiceActivityIds: ["spanish-verb-game-preterite", "spanish-verb-game-mixed"],
    relatedVocabIds: ["spanish-vocab-everyday"],
    recyclesObjectives: ["a1-present-tense-core"],
  },
  {
    id: "a1-present-progressive",
    tier: "basics",
    module: "Verbs",
    title: "Say what is happening right now",
    communicativeGoal: "Report actions in progress when reacting to the immediate moment.",
    status: "existing",
    canonicalGuideId: "spanish-present-progressive-guide",
    communicativeDomain: "real-time-actions",
    taskType: "interpersonal",
    interactionMode: "mixed",
    priority: "supporting",
    realWorldScenario: "You answer a call or message and explain what you are doing right now.",
    recommendedFor: ["adult-self-study", "conversation"],
    prerequisites: ["a1-present-tense-core", "a1-ser-estar"],
    relatedVocabIds: ["spanish-vocab-verbs", "spanish-common-verbs-flashcards"],
    recyclesObjectives: ["a1-present-tense-core", "a1-ser-estar"],
  },
  {
    id: "a2-immediate-future",
    tier: "basics",
    module: "Verbs",
    title: "Talk about plans and near-future intentions",
    communicativeGoal: "Explain what you are about to do and coordinate simple plans.",
    status: "existing",
    canonicalGuideId: "spanish-immediate-future-guide",
    communicativeDomain: "planning",
    taskType: "interpersonal",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You coordinate the next step in a plan, outing, or appointment.",
    recommendedFor: ["adult-self-study", "travel", "social"],
    prerequisites: ["a1-present-tense-core"],
    relatedVocabIds: ["spanish-vocab-everyday"],
    recyclesObjectives: ["a1-present-tense-core"],
  },
  {
    id: "a2-comparatives-superlatives",
    tier: "basics",
    module: "Core grammar distinctions",
    title: "Compare options and express preferences",
    communicativeGoal: "Compare people, places, and products while giving reasons for a choice.",
    status: "existing",
    canonicalGuideId: "spanish-comparatives-superlatives-guide",
    communicativeDomain: "shopping-and-choices",
    taskType: "interpersonal",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You compare hotels, restaurants, routes, or products before deciding.",
    recommendedFor: ["adult-self-study", "travel", "shopping"],
    prerequisites: ["a1-gender-articles", "a1-adjective-agreement"],
  },
  {
    id: "a2-obligation-necessity",
    tier: "basics",
    module: "Daily communication",
    title: "Explain obligations, needs, and next steps",
    communicativeGoal: "Say what must happen, what is needed, and what someone should do next.",
    status: "existing",
    canonicalGuideId: "spanish-obligation-necessity-guide",
    communicativeDomain: "daily-problem-solving",
    taskType: "interpersonal",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You explain requirements, errands, or what needs to happen in a situation.",
    recommendedFor: ["adult-self-study", "travel", "workplace-basics"],
    prerequisites: ["a1-present-tense-core"],
    relatedVocabIds: ["spanish-vocab-everyday", "spanish-common-verbs-flashcards"],
    recyclesObjectives: ["a1-present-tense-core"],
  },
  {
    id: "a2-commands-polite-requests",
    tier: "basics",
    module: "Daily communication",
    title: "Give instructions and soften requests",
    communicativeGoal: "Ask for action politely and give practical instructions in everyday settings.",
    status: "existing",
    canonicalGuideId: "spanish-commands-polite-requests-guide",
    communicativeDomain: "service-interactions",
    taskType: "interpersonal",
    interactionMode: "partner",
    priority: "core",
    realWorldScenario: "You need to ask for help, give directions, or tell someone how to do something.",
    recommendedFor: ["adult-self-study", "travel", "customer-service"],
    prerequisites: ["a1-present-tense-core"],
  },
  {
    id: "a2-object-pronouns-basics",
    tier: "basics",
    module: "Core grammar distinctions",
    title: "Handle common references without repeating nouns",
    communicativeGoal: "Keep short conversations moving by referring back to people and things naturally.",
    status: "existing",
    canonicalGuideId: "spanish-object-pronouns-basics-guide",
    communicativeDomain: "conversation-management",
    taskType: "interpersonal",
    interactionMode: "mixed",
    priority: "supporting",
    realWorldScenario: "You order, ask for, or offer items without repeating the full noun every time.",
    recommendedFor: ["adult-self-study", "conversation"],
    prerequisites: ["a1-present-tense-core", "a1-gender-articles"],
  },
  {
    id: "a2-reflexive-routines",
    tier: "basics",
    module: "Daily communication",
    title: "Describe personal routines and self-care habits",
    communicativeGoal: "Talk through daily routines in a way that sounds natural in Spanish.",
    status: "existing",
    canonicalGuideId: "spanish-reflexive-verbs-routines-guide",
    communicativeDomain: "daily-life",
    taskType: "presentational",
    interactionMode: "solo",
    priority: "core",
    realWorldScenario: "You explain your morning, evening, or workday routine.",
    recommendedFor: ["adult-self-study", "conversation"],
    relatedVocabIds: ["spanish-vocab-everyday"],
    recyclesObjectives: ["a1-present-tense-core", "a1-ser-estar"],
  },
  {
    id: "a2-travel-conversations",
    tier: "basics",
    module: "Daily communication",
    title: "Handle core travel interactions independently",
    communicativeGoal: "Ask for help, check in, get directions, and respond to travel problems in Spanish.",
    status: "existing",
    canonicalGuideId: "spanish-travel-conversations-guide",
    communicativeDomain: "travel",
    taskType: "integrated",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You land in a Spanish-speaking city and need to manage airport, hotel, and emergency interactions.",
    recommendedFor: ["adult-self-study", "travel"],
    prerequisites: ["a1-present-tense-core", "a1-ser-estar"],
    relatedVocabIds: ["spanish-vocab-everyday"],
    recyclesObjectives: ["a1-present-tense-core", "a2-immediate-future"],
  },
  {
    id: "b1-present-perfect",
    tier: "intermediate",
    module: "Verb systems",
    title: "Connect present relevance to past experience",
    communicativeGoal: "Talk about experiences and recent past events that matter now.",
    status: "existing",
    canonicalGuideId: "spanish-present-perfect-b1-guide",
    communicativeDomain: "personal-experience",
    taskType: "interpersonal",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You update someone on what has happened recently and why it matters now.",
    recommendedFor: ["adult-self-study", "conversation", "workplace-basics"],
    prerequisites: ["a2-past-tenses"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b1-connectors-argumentation",
    tier: "intermediate",
    module: "Discourse development",
    title: "State and support an opinion in connected discourse",
    communicativeGoal: "Organize short arguments with clear links between ideas.",
    status: "existing",
    canonicalGuideId: "spanish-conectores-argumentacion-b1-guide",
    communicativeDomain: "opinions-and-argument",
    taskType: "presentational",
    interactionMode: "solo",
    priority: "core",
    realWorldScenario: "You explain your view on a choice, policy, or preference with brief support.",
    recommendedFor: ["adult-self-study", "academic", "workplace-basics"],
    prerequisites: ["a2-comparatives-superlatives", "a2-commands-polite-requests"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b1-subjunctive-intro",
    tier: "intermediate",
    module: "Mood and modality",
    title: "Express wishes, doubt, and recommendations",
    communicativeGoal: "Say what you want, recommend, or are unsure about in real interactions.",
    status: "existing",
    canonicalGuideId: "spanish-subjuntivo-intro-b1-guide",
    communicativeDomain: "advice-and-attitude",
    taskType: "interpersonal",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You recommend actions, react emotionally, or express uncertainty in conversation.",
    recommendedFor: ["adult-self-study", "conversation", "workplace-basics"],
    prerequisites: ["a2-immediate-future"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b1-integrated-assessment",
    tier: "intermediate",
    module: "Integrated performance",
    title: "Complete a mid-level integrated communication task",
    communicativeGoal: "Read, interpret, and respond to a practical task using connected Spanish.",
    status: "existing",
    canonicalGuideId: "spanish-b1-integrated-assessment-guide",
    communicativeDomain: "integrated-performance",
    taskType: "integrated",
    interactionMode: "solo",
    priority: "core",
    realWorldScenario: "You read source material and produce a short response or mini-project.",
    recommendedFor: ["adult-self-study", "academic", "assessment"],
    prerequisites: ["b1-present-perfect", "b1-subjunctive-intro"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b2-subjunctive-system",
    tier: "intermediate",
    module: "Mood and modality",
    title: "Manage dependent-clause meaning precisely",
    communicativeGoal: "Control clause choice when evaluating, doubting, or qualifying information.",
    status: "existing",
    canonicalGuideId: "spanish-subjuntivo-clausulas-b2-guide",
    communicativeDomain: "nuanced-expression",
    taskType: "presentational",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You respond to complex statements where certainty, evaluation, and dependency matter.",
    recommendedFor: ["adult-self-study", "academic", "professional"],
    prerequisites: ["b1-subjunctive-intro"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b2-tense-mood-contrast",
    tier: "intermediate",
    module: "Advanced discourse control",
    title: "Choose tense and mood for nuanced workplace and academic meaning",
    communicativeGoal: "Make precise choices about time, stance, and hypothesis in advanced contexts.",
    status: "existing",
    canonicalGuideId: "spanish-contraste-tiempos-b2-guide",
    communicativeDomain: "academic-and-workplace",
    taskType: "integrated",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You summarize, clarify, and qualify information in work or study settings.",
    recommendedFor: ["adult-self-study", "academic", "professional"],
    prerequisites: ["b1-present-perfect", "b1-subjunctive-intro", "b2-subjunctive-system"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b2-passive-impersonal-se",
    tier: "intermediate",
    module: "Advanced discourse control",
    title: "Report formal processes and impersonal information",
    communicativeGoal: "Describe procedures and formal statements without overusing personal subjects.",
    status: "existing",
    canonicalGuideId: "spanish-pasiva-impersonales-b2-guide",
    communicativeDomain: "formal-information",
    taskType: "presentational",
    interactionMode: "solo",
    priority: "supporting",
    realWorldScenario: "You explain procedures, notices, or institutional information in a formal register.",
    recommendedFor: ["adult-self-study", "academic", "professional"],
    prerequisites: ["b1-subjunctive-intro", "b2-subjunctive-system"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b2-integrated-assessment",
    tier: "intermediate",
    module: "Integrated performance",
    title: "Synthesize sources and respond with a reasoned position",
    communicativeGoal: "Interpret multiple inputs and produce a coherent argument or synthesis.",
    status: "existing",
    canonicalGuideId: "spanish-b2-integrated-assessment-guide",
    communicativeDomain: "integrated-performance",
    taskType: "integrated",
    interactionMode: "solo",
    priority: "core",
    realWorldScenario: "You combine reading and listening input into a clear written or spoken response.",
    recommendedFor: ["adult-self-study", "academic", "assessment"],
    prerequisites: ["b2-subjunctive-system", "b2-tense-mood-contrast", "b2-passive-impersonal-se"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c1-register-control",
    tier: "advanced",
    module: "Advanced production",
    title: "Shift tone and register intentionally",
    communicativeGoal: "Adjust how you sound depending on audience, distance, and purpose.",
    status: "existing",
    canonicalGuideId: "spanish-register-control-c1-guide",
    communicativeDomain: "register-and-tone",
    taskType: "presentational",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You rewrite or respond differently for a friend, colleague, or formal audience.",
    recommendedFor: ["adult-self-study", "professional", "academic"],
    prerequisites: ["b2-subjunctive-system"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c1-connectors-persuasion",
    tier: "advanced",
    module: "Advanced production",
    title: "Build persuasive, well-organized arguments",
    communicativeGoal: "Guide a reader or listener through a structured persuasive message.",
    status: "existing",
    canonicalGuideId: "spanish-conectores-persuasion-c1-guide",
    communicativeDomain: "persuasion",
    taskType: "presentational",
    interactionMode: "solo",
    priority: "core",
    realWorldScenario: "You write or deliver a persuasive message with clear logic and cohesion.",
    recommendedFor: ["adult-self-study", "academic", "professional"],
    prerequisites: ["c1-register-control", "b2-tense-mood-contrast"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c1-production-lab",
    tier: "advanced",
    module: "Integrated performance",
    title: "Draft, revise, and improve extended production",
    communicativeGoal: "Produce longer Spanish texts and refine them against clear communicative criteria.",
    status: "existing",
    canonicalGuideId: "spanish-c1-production-lab-guide",
    communicativeDomain: "extended-production",
    taskType: "integrated",
    interactionMode: "solo",
    priority: "core",
    realWorldScenario: "You draft and revise an essay or long-form response with explicit criteria.",
    recommendedFor: ["adult-self-study", "academic", "professional"],
    prerequisites: ["c1-register-control", "c1-connectors-persuasion"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c1-esol-teacher-contrastive",
    tier: "intermediate",
    module: "Applied learning",
    title: "Use an ESOL-teacher lens to map Spanish more efficiently",
    communicativeGoal: "Leverage teaching knowledge to anticipate interference and teach-yourself patterns faster.",
    status: "existing",
    canonicalGuideId: "spanish-for-esol-teachers-guide",
    communicativeDomain: "teacher-transfer",
    taskType: "integrated",
    interactionMode: "solo",
    priority: "specialized",
    realWorldScenario: "You compare English-teaching categories with Spanish structures to accelerate learning.",
    recommendedFor: ["esol-teachers"],
    prerequisites: ["b2-tense-mood-contrast"],
    notes: "Guide is in English for ESOL teachers learning Spanish.",
  },
  {
    id: "c2-pragmatic-nuance",
    tier: "advanced",
    module: "Mastery",
    title: "Control nuance, stance, and implied meaning",
    communicativeGoal: "Interpret and produce subtle meaning where tone and implication matter as much as grammar.",
    status: "existing",
    canonicalGuideId: "spanish-matices-pragmaticos-c2-guide",
    communicativeDomain: "pragmatics",
    taskType: "integrated",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You navigate delicate professional, academic, or interpersonal situations where nuance matters.",
    recommendedFor: ["adult-self-study", "professional", "academic"],
    prerequisites: ["c1-register-control", "c1-connectors-persuasion", "c1-production-lab"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c2-precision-lab",
    tier: "advanced",
    module: "Mastery",
    title: "Diagnose and reformulate subtle errors",
    communicativeGoal: "Notice small problems in word choice, tone, and structure and repair them precisely.",
    status: "existing",
    canonicalGuideId: "spanish-precision-lab-c2-guide",
    communicativeDomain: "precision-editing",
    taskType: "integrated",
    interactionMode: "solo",
    priority: "core",
    realWorldScenario: "You revise advanced Spanish so it sounds accurate, natural, and purposeful.",
    recommendedFor: ["adult-self-study", "professional", "academic"],
    prerequisites: ["c2-pragmatic-nuance"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c2-precision-rewriting",
    tier: "advanced",
    module: "Mastery",
    title: "Rewrite for near-native precision",
    communicativeGoal: "Recast messages so they sound more precise, idiomatic, and context-appropriate.",
    status: "existing",
    canonicalGuideId: "spanish-precision-lab-c2-guide",
    communicativeDomain: "precision-editing",
    taskType: "presentational",
    interactionMode: "solo",
    priority: "supporting",
    realWorldScenario: "You are given a workable message and must rewrite it for sharper control and naturalness.",
    recommendedFor: ["adult-self-study", "professional", "academic"],
    prerequisites: ["c2-pragmatic-nuance"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c2-capstone",
    tier: "advanced",
    module: "Integrated performance",
    title: "Complete a high-stakes professional or academic simulation",
    communicativeGoal: "Integrate reading, listening, writing, and speaking under realistic constraints.",
    status: "existing",
    canonicalGuideId: "spanish-c2-capstone-guide",
    communicativeDomain: "capstone-simulation",
    taskType: "integrated",
    interactionMode: "mixed",
    priority: "core",
    realWorldScenario: "You manage an advanced real-world simulation that demands multiple skills at once.",
    recommendedFor: ["adult-self-study", "professional", "academic", "assessment"],
    prerequisites: ["c2-pragmatic-nuance", "c2-precision-lab"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
];
