import type { SpanishTier } from "./registry";

export type SpanishObjectiveStatus = "existing" | "planned";

export interface SpanishCourseObjective {
  id: string;
  tier: SpanishTier;
  module: string;
  title: string;
  status: SpanishObjectiveStatus;
  canonicalGuideId?: string;
  practiceActivityIds?: string[];
  /** Vocab/flashcard activities that support this objective. */
  relatedVocabIds?: string[];
  /** Objective IDs this guide recycles (spiral review). */
  recyclesObjectives?: string[];
  prerequisites?: string[];
  notes?: string;
}

/** Canonical roadmap by tier (Basics, Intermediate, Advanced) to prevent overlap and track objectives. */
export const spanishCourseObjectives: SpanishCourseObjective[] = [
  {
    id: "a1-alphabet-pronunciation",
    tier: "basics",
    module: "Foundations",
    title: "Alphabet and pronunciation basics",
    status: "existing",
    canonicalGuideId: "spanish-alphabet-pronunciation-guide",
  },
  {
    id: "a1-gender-articles",
    tier: "basics",
    module: "Foundations",
    title: "Noun gender and articles",
    status: "existing",
    canonicalGuideId: "spanish-noun-gender-articles-guide",
  },
  {
    id: "a1-present-tense-core",
    tier: "basics",
    module: "Verbs",
    title: "Present tense core usage",
    status: "existing",
    canonicalGuideId: "spanish-present-tense-guide",
    practiceActivityIds: [
      "spanish-verb-game-present-ar",
      "spanish-verb-game-present-er-ir",
      "spanish-verb-game-present-irregular",
    ],
    relatedVocabIds: ["spanish-vocab-verbs", "spanish-common-verbs-flashcards"],
    recyclesObjectives: ["a1-gender-articles"],
  },
  {
    id: "a1-ser-estar",
    tier: "basics",
    module: "Core grammar distinctions",
    title: "Ser vs estar basics",
    status: "existing",
    canonicalGuideId: "spanish-ser-vs-estar-guide",
  },
  {
    id: "a1-adjective-agreement",
    tier: "basics",
    module: "Core grammar distinctions",
    title: "Adjective agreement by gender and number",
    status: "existing",
    canonicalGuideId: "spanish-adjective-agreement-guide",
  },
  {
    id: "a2-past-tenses",
    tier: "basics",
    module: "Verbs",
    title: "Preterite and imperfect contrast",
    status: "existing",
    canonicalGuideId: "spanish-imperfect-tense-guide",
    prerequisites: ["a1-present-tense-core"],
    practiceActivityIds: ["spanish-verb-game-preterite", "spanish-verb-game-mixed"],
    relatedVocabIds: ["spanish-vocab-everyday"],
    recyclesObjectives: ["a1-present-tense-core"],
  },
  {
    id: "a1-present-progressive",
    tier: "basics",
    module: "Verbs",
    title: "Present progressive (estar + gerund)",
    status: "existing",
    canonicalGuideId: "spanish-present-progressive-guide",
    prerequisites: ["a1-present-tense-core", "a1-ser-estar"],
    relatedVocabIds: ["spanish-vocab-verbs", "spanish-common-verbs-flashcards"],
    recyclesObjectives: ["a1-present-tense-core", "a1-ser-estar"],
  },
  {
    id: "a2-immediate-future",
    tier: "basics",
    module: "Verbs",
    title: "Immediate future with ir + a + infinitive",
    status: "existing",
    canonicalGuideId: "spanish-immediate-future-guide",
    prerequisites: ["a1-present-tense-core"],
    relatedVocabIds: ["spanish-vocab-everyday"],
    recyclesObjectives: ["a1-present-tense-core"],
  },
  {
    id: "a2-comparatives-superlatives",
    tier: "basics",
    module: "Core grammar distinctions",
    title: "Comparatives and superlatives in context",
    status: "existing",
    canonicalGuideId: "spanish-comparatives-superlatives-guide",
    prerequisites: ["a1-gender-articles", "a1-adjective-agreement"],
  },
  {
    id: "a2-obligation-necessity",
    tier: "basics",
    module: "Daily communication",
    title: "Obligation and necessity (tener que, deber, necesitar)",
    status: "existing",
    canonicalGuideId: "spanish-obligation-necessity-guide",
    prerequisites: ["a1-present-tense-core"],
    relatedVocabIds: ["spanish-vocab-everyday", "spanish-common-verbs-flashcards"],
    recyclesObjectives: ["a1-present-tense-core"],
  },
  {
    id: "a2-commands-polite-requests",
    tier: "basics",
    module: "Daily communication",
    title: "Commands and polite requests (tú/usted)",
    status: "existing",
    canonicalGuideId: "spanish-commands-polite-requests-guide",
    prerequisites: ["a1-present-tense-core"],
  },
  {
    id: "a2-object-pronouns-basics",
    tier: "basics",
    module: "Core grammar distinctions",
    title: "Direct and indirect object pronouns",
    status: "existing",
    canonicalGuideId: "spanish-object-pronouns-basics-guide",
    prerequisites: ["a1-present-tense-core", "a1-gender-articles"],
  },
  {
    id: "a2-reflexive-routines",
    tier: "basics",
    module: "Daily communication",
    title: "Reflexive verbs and daily routines",
    status: "existing",
    canonicalGuideId: "spanish-reflexive-verbs-routines-guide",
    relatedVocabIds: ["spanish-vocab-everyday"],
    recyclesObjectives: ["a1-present-tense-core", "a1-ser-estar"],
  },
  {
    id: "a2-travel-conversations",
    tier: "basics",
    module: "Daily communication",
    title: "Travel conversations (airport, hotel, directions, emergencies)",
    status: "existing",
    canonicalGuideId: "spanish-travel-conversations-guide",
    prerequisites: ["a1-present-tense-core", "a1-ser-estar"],
    relatedVocabIds: ["spanish-vocab-everyday"],
    recyclesObjectives: ["a1-present-tense-core", "a2-immediate-future"],
  },
  {
    id: "b1-present-perfect",
    tier: "intermediate",
    module: "Verb systems",
    title: "Present perfect and contrast with past tenses",
    status: "existing",
    canonicalGuideId: "spanish-present-perfect-b1-guide",
    prerequisites: ["a2-past-tenses"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b1-connectors-argumentation",
    tier: "intermediate",
    module: "Discourse development",
    title: "Discourse connectors and short-form argumentation",
    status: "existing",
    canonicalGuideId: "spanish-conectores-argumentacion-b1-guide",
    prerequisites: ["a2-comparatives-superlatives", "a2-commands-polite-requests"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b1-subjunctive-intro",
    tier: "intermediate",
    module: "Mood and modality",
    title: "Introduction to present subjunctive",
    status: "existing",
    canonicalGuideId: "spanish-subjuntivo-intro-b1-guide",
    prerequisites: ["a2-immediate-future"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b1-integrated-assessment",
    tier: "intermediate",
    module: "Integrated performance",
    title: "Integrated reading, writing, and mini-project assessment",
    status: "existing",
    canonicalGuideId: "spanish-b1-integrated-assessment-guide",
    prerequisites: ["b1-present-perfect", "b1-subjunctive-intro"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b2-subjunctive-system",
    tier: "intermediate",
    module: "Mood and modality",
    title: "Subjunctive in dependent clauses",
    status: "existing",
    canonicalGuideId: "spanish-subjuntivo-clausulas-b2-guide",
    prerequisites: ["b1-subjunctive-intro"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b2-tense-mood-contrast",
    tier: "intermediate",
    module: "Advanced discourse control",
    title: "Fine-grained tense and mood contrast in academic/work contexts",
    status: "existing",
    canonicalGuideId: "spanish-contraste-tiempos-b2-guide",
    prerequisites: ["b1-present-perfect", "b1-subjunctive-intro", "b2-subjunctive-system"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b2-passive-impersonal-se",
    tier: "intermediate",
    module: "Advanced discourse control",
    title: "Passive voice and impersonal se in formal communication",
    status: "existing",
    canonicalGuideId: "spanish-pasiva-impersonales-b2-guide",
    prerequisites: ["b1-subjunctive-intro", "b2-subjunctive-system"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "b2-integrated-assessment",
    tier: "intermediate",
    module: "Integrated performance",
    title: "Integrated reading, audio synthesis, and argument response",
    status: "existing",
    canonicalGuideId: "spanish-b2-integrated-assessment-guide",
    prerequisites: ["b2-subjunctive-system", "b2-tense-mood-contrast", "b2-passive-impersonal-se"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c1-register-control",
    tier: "advanced",
    module: "Advanced production",
    title: "Register, tone, and argumentation control",
    status: "existing",
    canonicalGuideId: "spanish-register-control-c1-guide",
    prerequisites: ["b2-subjunctive-system"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c1-connectors-persuasion",
    tier: "advanced",
    module: "Advanced production",
    title: "Advanced connectors and persuasive discourse organization",
    status: "existing",
    canonicalGuideId: "spanish-conectores-persuasion-c1-guide",
    prerequisites: ["c1-register-control", "b2-tense-mood-contrast"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c1-production-lab",
    tier: "advanced",
    module: "Integrated performance",
    title: "Essay production lab with rubric-based revision",
    status: "existing",
    canonicalGuideId: "spanish-c1-production-lab-guide",
    prerequisites: ["c1-register-control", "c1-connectors-persuasion"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c1-esol-teacher-contrastive",
    tier: "intermediate",
    module: "Applied learning",
    title: "Spanish for ESOL teachers (contrastive guide)",
    status: "existing",
    canonicalGuideId: "spanish-for-esol-teachers-guide",
    prerequisites: ["b2-tense-mood-contrast"],
    notes: "Guide is in English for ESOL teachers learning Spanish.",
  },
  {
    id: "c2-pragmatic-nuance",
    tier: "advanced",
    module: "Mastery",
    title: "Pragmatic nuance, intent, and tone control in complex contexts",
    status: "existing",
    canonicalGuideId: "spanish-matices-pragmaticos-c2-guide",
    prerequisites: ["c1-register-control", "c1-connectors-persuasion", "c1-production-lab"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c2-precision-lab",
    tier: "advanced",
    module: "Mastery",
    title: "Subtle error correction and high-precision reformulation",
    status: "existing",
    canonicalGuideId: "spanish-precision-lab-c2-guide",
    prerequisites: ["c2-pragmatic-nuance"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c2-precision-rewriting",
    tier: "advanced",
    module: "Mastery",
    title: "Near-native precision and rewriting",
    status: "existing",
    canonicalGuideId: "spanish-precision-lab-c2-guide",
    prerequisites: ["c2-pragmatic-nuance"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
  {
    id: "c2-capstone",
    tier: "advanced",
    module: "Integrated performance",
    title: "Integrated professional/academic simulation capstone",
    status: "existing",
    canonicalGuideId: "spanish-c2-capstone-guide",
    prerequisites: ["c2-pragmatic-nuance", "c2-precision-lab"],
    notes: "Spanish-only for instructions, hints, and feedback.",
  },
];
